# A guide Portfolio Optimization Environment

This notebook aims to provide an example of using PortfolioOptimizationEnv (or POE) to train a reinforcement learning model that learns to solve the portfolio optimization problem.

In this document, we will reproduce a famous architecture called EIIE (ensemble of identical independent evaluators), introduced in the following paper:

- Zhengyao Jiang, Dixing Xu, & Jinjun Liang. (2017). A Deep Reinforcement Learning Framework for the Financial Portfolio Management Problem. https://doi.org/10.48550/arXiv.1706.10059.

It's advisable to read it to understand the algorithm implemented in this notebook.

### Note
If you're using this environment, consider citing the following paper (in adittion to FinRL references):

- Caio Costa, & Anna Costa (2023). POE: A General Portfolio Optimization Environment for FinRL. In *Anais do II Brazilian Workshop on Artificial Intelligence in Finance* (pp. 132–143). SBC. https://doi.org/10.5753/bwaif.2023.231144.

```
@inproceedings{bwaif,
 author = {Caio Costa and Anna Costa},
 title = {POE: A General Portfolio Optimization Environment for FinRL},
 booktitle = {Anais do II Brazilian Workshop on Artificial Intelligence in Finance},
 location = {João Pessoa/PB},
 year = {2023},
 keywords = {},
 issn = {0000-0000},
 pages = {132--143},
 publisher = {SBC},
 address = {Porto Alegre, RS, Brasil},
 doi = {10.5753/bwaif.2023.231144},
 url = {https://sol.sbc.org.br/index.php/bwaif/article/view/24959}
}

```

## Installation and imports

To run this notebook in google colab, uncomment the cells below.

In [ ]:
## install finrl library
# !sudo apt install swig
# !pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
swig is already the newest version (4.2.0-2ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.

In [ ]:
## We also need to install quantstats, because the environment uses it to plot graphs
# !pip install quantstats

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting quantstats
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/cc/74/b9cf9a2cf911d48c120635b71281a3a28323e97813e7a4d459b6acfd6447/QuantStats-0.0.64-py2.py3-none-any.whl (45 kB)
Requirement already satisfied: pandas>=0.24.0 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from quantstats) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from quantstats) (2.2.4)
Requirement already satisfied: seaborn>=0.9.0 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from quantstats) (0.13.2)
Requirement already satisfied: matplotlib>=3.0.0 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from quantstats) (3.10.1)
Requirement already satisfied: scipy>=1.2.0 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from quantstats) (1.15.2)
Collecting tabulate>=0.8.0 (from quantstats)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/40/44/4a5f08c96eb108af5cb50b41f76142f0afa346dfa99d5296fe7202a11854/tabulate-0.9.0-py3-none-any.whl (35 kB)
Requirement already satisfied: yfinance>=0.1.70 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from quantstats) (0.2.55)
Requirement already satisfied: python-dateutil>=2.0 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from quantstats) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from matplotlib>=3.0.0->quantstats) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from matplotlib>=3.0.0->quantstats) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from matplotlib>=3.0.0->quantstats) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from matplotlib>=3.0.0->quantstats) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from matplotlib>=3.0.0->quantstats) (24.2)
Requirement already satisfied: pillow>=8 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from matplotlib>=3.0.0->quantstats) (11.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from matplotlib>=3.0.0->quantstats) (3.2.3)
Requirement already satisfied: pytz>=2020.1 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from pandas>=0.24.0->quantstats) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from pandas>=0.24.0->quantstats) (2025.2)
Requirement already satisfied: six>=1.5 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from python-dateutil>=2.0->quantstats) (1.17.0)
Requirement already satisfied: requests>=2.31 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from yfinance>=0.1.70->quantstats) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from yfinance>=0.1.70->quantstats) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from yfinance>=0.1.70->quantstats) (4.3.7)
Requirement already satisfied: frozendict>=2.3.4 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from yfinance>=0.1.70->quantstats) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from yfinance>=0.1.70->quantstats) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from yfinance>=0.1.70->quantstats) (4.13.3)
Requirement already satisfied: soupsieve>1.2 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance>=0.1.70->quantstats) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance>=0.1.70->quantstats) (4.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from requests>=2.31->yfinance>=0.1.70->quantstats) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from requests>=2.31->yfinance>=0.1.70->quantstats) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from requests>=2.31->yfinance>=0.1.70->quantstats) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /home/stock/miniconda3/envs/finstock/lib/python3.10/site-packages (from requests>=2.31->yfinance>=0.1.70->quantstats) (2025.1.31)
Installing collected packages: tabulate, quantstats
Successfully installed quantstats-0.0.64 tabulate-0.9.0

In [4]:
## Hide matplotlib warnings
# import warnings
# warnings.filterwarnings('ignore')

import logging
logging.getLogger('matplotlib.font_manager').disabled = True

#### Import the necessary code libraries

In [5]:
import pandas as pd
import yfinance as yf
from datetime import datetime
class YahooRealtimeDownloader:
    """
    Provides methods for retrieving near-real-time (1-minute) stock data
    from Yahoo Finance API, returning only the last available bar or
    "one minute behind" the latest bar.
    """

    def __init__(self, ticker_list: list):
        """
        Parameters
        ----------
        ticker_list: list
            a list of stock tickers
        """
        self.ticker_list = ticker_list

    def fetch_data(self, proxy=None, pick_second_to_last=True) -> pd.DataFrame:
        """
        Fetches near-real-time 1-minute data from Yahoo API for the current day.
        """
        import datetime
        data_df = pd.DataFrame()
        num_failures = 0

        # 按照 1 分钟周期下载当日数据
        for tic in self.ticker_list:
            temp_df = yf.download(
                tickers=tic,
                period='1d',
                interval='1m',
                proxy=proxy,
                progress=False
            )

            temp_df["tic"] = tic

            if len(temp_df) > 0:
                # 如果您想获取倒数第二条数据
                if pick_second_to_last and len(temp_df) > 1:
                    temp_df = temp_df.iloc[[-2]]  # 取倒数第二行
                else:
                    temp_df = temp_df.iloc[[-1]]

                data_df = pd.concat([data_df, temp_df], axis=0)
            else:
                num_failures += 1

        if num_failures == len(self.ticker_list):
            raise ValueError("No data is fetched. Possibly all tickers returned empty for today.")

        # reset the index
        data_df = data_df.reset_index()

        # rename columns
        try:
            data_df.columns = [
                "date",
                "open",
                "high",
                "low",
                "close",
                "adjcp",
                "volume",
                "tic",
            ]
            data_df["close"] = data_df["adjcp"]
            data_df = data_df.drop(labels="adjcp", axis=1)
        except ValueError:
            print("Columns might not match the expected format; please check yfinance returned columns.")

        # 将日期列转换为 datetime
        data_df["date"] = pd.to_datetime(data_df["date"])
        
        # 获取本地当前日期，例如 2023-10-10
        today = datetime.date.today()

        # 如果行里的 date 不是当天，就改为当天；去掉时分秒，保留 YYYY-MM-DD
        def fix_date(dt):
            if dt.date() != today:
                return today.strftime('%Y-%m-%d')
            else:
                return dt.strftime('%Y-%m-%d')

        data_df["date"] = data_df["date"].apply(fix_date)

        # 再创建 day 列，这里仅保留日期而无时分秒，所以先转回 datetime
        data_df["date"] = pd.to_datetime(data_df["date"])
        data_df["day"] = data_df["date"].dt.dayofweek
        data_df["date"] = data_df["date"].dt.strftime("%Y-%m-%d")

        data_df = data_df.dropna().reset_index(drop=True)

        data_df = data_df.sort_values(by=["date", "tic"]).reset_index(drop=True)

        print("Shape of realtime DataFrame: ", data_df.shape)
        print(data_df)
        return data_df

In [8]:
from IPython import get_ipython

ip = get_ipython()
if not hasattr(ip, 'magic'):
    ip.magic = lambda x: None  # 或者提供更加完整的实现
import torch

import numpy as np

from sklearn.preprocessing import MaxAbsScaler

import sys
import os

# 获取当前文件的绝对路径，并向上追溯两级到项目根目录
project_root = os.path.dirname(os.path.abspath(os.getcwd()))
print(project_root)
sys.path.append(project_root)

from finrl.meta.preprocessor.tusharedownloader import TushareDownloader
from finrl.meta.preprocessor.preprocessors import GroupByScaler
from finrl.meta.env_portfolio_optimization.env_portfolio_optimization import PortfolioOptimizationEnv
from finrl.agents.portfolio_optimization.models import DRLAgent
from finrl.agents.portfolio_optimization.architectures import EIIE

device = 'cuda:0' if torch.cuda.is_available() else 'cpu'

/home/stock/projects/finstock/FinRL

## Fetch data

In his paper, *Jiang et al* creates a portfolio composed by the top-11 cryptocurrencies based on 30-days volume. Since it's not specified when this classification was done, it's difficult to reproduce, so we will use a similar approach in the Brazillian stock market:

- We select top-10 stocks from Brazillian stock market;
- For simplicity, we disconsider stocks that have missing data for the days in period 2011-01-01 to 2019-12-31 (9 years);

In [2]:
market = "ch"
if market.lower() == "us":
    TOP_BRL = [
        'BILI', 'DUO', 'NIO', 'JD', 'YINN', 'YANG', 'FUTU','XHG','BABA','PDD','RGTI'
    ]
elif market.lower() == "hk":
    TOP_BRL = [
         '1812.hk', '3900.hk', '2777.hk', '1810.hk', '2878.HK','0029.hk'
    ]
elif market.lower() == "ch":
    TOP_BRL = [
         '603063.ss', '603319.ss', '000657.sz','002640.sz','002664.sz','300182.sz','688200.SS','002850.SZ'
    ]

    # TOP_BRL = [
    # '000063.SZ',
    # '002068.SZ',
    # '002138.SZ',
    # '002779.SZ',
    # '002850.SZ',
    # '300408.SZ',
    # '300442.SZ',
    # '300657.SZ',
    # '300673.SZ',
    # '300909.SZ',
    # '300913.SZ',
    # '601111.SS',
    # '601689.SS',
    # '603063.SS',
    # '603236.SS',
    # '603305.SS',
    # '603556.SS',
    # '603667.SS',
    # '688088.SS',
    # '688160.SS',
    # '688200.SS']
else:
    raise ValueError("market 变量必须为 'us' 或 'hk'")

print("当前选择的市场:", market)
print("股票列表:", TOP_BRL)
# '9988.hk',,'1797.hk''1918.hk', '3319.hk',

当前选择的市场: ch
股票列表: ['603063.ss', '603319.ss', '000657.sz', '002640.sz', '002664.sz', '300182.sz', '688200.SS', '002850.SZ']

In [ ]:
# 原有数据获取方式（保持不变）
print(len(TOP_BRL))

portfolio_raw_df = TushareDownloader(start_date = '2022-01-01',
                                end_date = '2025-03-26',
                                ticker_list = TOP_BRL).fetch_data()

# 展示如何在未来使用 PoE 数据管道
print("\n" + "="*60)
print("🚀 如何使用 PoE 数据管道 (未来升级)")
print("="*60)
print("""
# 1. 使用 PoE 数据管道和过滤器的示例代码:
from poe.core.config import FinRLConfig
from poe.core.protfolioexperiment import PortfolioOptimizationExperiment

# 2. 配置 PoE (包含节假日过滤)
poe_config = FinRLConfig(
    top_brl=TOP_BRL,
    features=["close", "high", "low", "volume"],
    time_window=4,
    user_id=1,
    group_id=1,
    date_range={
        "train_start": "2022-01-01",
        "train_end": "2024-03-01", 
        "test_start": "2024-03-01",
        "test_end": "2025-03-26"
    },
    # 节假日过滤器 (插件化)
    date_filters=[
        {
            "name": "chinese_holidays",
            "config": {
                "days_before": 15,    # 节前15天
                "days_after": 10,     # 节后10天
                "holidays": ['春节', '五一', '国庆']
            }
        }
    ]
)

# 3. 获取处理好的数据
exp = PortfolioOptimizationExperiment(poe_config)
env_train, env_test, df_train, df_test = exp._setup_training_environment()
portfolio_raw_df = pd.concat([df_train, df_test], ignore_index=True)
""")
print("="*60)

portfolio_raw_df

In [11]:
# realtime_df = YahooRealtimeDownloader(ticker_list = TOP_BRL).fetch_data()
# 假设这两个 DataFrame 的列名相同 
# portfolio_raw_df = pd.concat([portfolio_raw_df, realtime_df], ignore_index=True)

# 对合并后的数据，根据日期和股票标的排序，并重新索引
portfolio_raw_df = portfolio_raw_df.sort_values(["date", "tic"]).reset_index(drop=True)

# 检查合并后的数据
print(portfolio_raw_df.head())
print(portfolio_raw_df.tail())

         date    open    high     low   close      volume        tic  day
0  2022-01-04   16.08   16.19   15.20   15.22   264158.22  000657.sz    1
1  2022-01-04    3.08    3.29    3.08    3.29   535143.14  002640.sz    1
2  2022-01-04   20.30   20.78   20.01   20.26    41189.89  002664.sz    1
3  2022-01-04  164.00  164.00  151.51  153.20    28140.37  002850.SZ    1
4  2022-01-04    6.60    6.77    6.36    6.54  3033080.78  300182.sz    1
            date    open    high     low   close      volume        tic  day
4340  2024-12-31    4.04    4.10    3.80    3.84  1457282.32  002640.sz    1
4341  2024-12-31   14.22   14.59   13.99   14.06    96976.00  002664.sz    1
4342  2024-12-31   98.91   99.35   95.92   97.68    28392.89  002850.SZ    1
4343  2024-12-31    6.27    6.32    5.85    5.87  1159665.50  300182.sz    1
4344  2024-12-31  105.13  107.78  104.00  104.50    31618.92  688200.SH    1

In [12]:
from finrl.config import INDICATORS
from finrl.meta.preprocessor.preprocessors import FeatureEngineer
fe = FeatureEngineer(
    use_technical_indicator=True,
    tech_indicator_list=INDICATORS,
    use_vix=False,
    use_turbulence=False,
    user_defined_feature=False
)
processed = fe.preprocess_data(portfolio_raw_df)
logging.info("数据预处理完成。")

基准日期范围从 2022-01-04 到 2024-12-31
merged_closes 的列名: Index(['000657.sz', '002640.sz', '002664.sz', '002850.SZ', '300182.sz',
       '688200.SH'],
      dtype='object', name='tic')
merged_closes 的索引名: None
reset_index 后的列名: Index(['date', '000657.sz', '002640.sz', '002664.sz', '002850.SZ', '300182.sz',
       '688200.SH'],
      dtype='object', name='tic')
最终股票代码 000657.sz 的日期一致，日期数量: 726
最终股票代码 002640.sz 的日期一致，日期数量: 726
最终股票代码 002664.sz 的日期一致，日期数量: 726
最终股票代码 002850.SZ 的日期一致，日期数量: 726
最终股票代码 300182.sz 的日期一致，日期数量: 726
最终股票代码 688200.SH 的日期一致，日期数量: 726
Successfully added technical indicators

In [ ]:
# from feature.ch_feature_engineer import ChFeatureEngineer
# ch_fe = ChFeatureEngineer()
# portfolio_processed = ch_fe.preprocess_data(processed)
# logging.info("自定义特征工程完成。")

In [ ]:
# PoE 数据管道已经应用了节假日过滤器，直接使用处理好的数据
print("✅ PoE 数据管道已自动应用节假日过滤器")
print("🎊 节假日过滤配置: 春节、五一、国庆前15天+后10天")

# 数据已经通过 PoE 管道处理，包含节假日过滤
filtered_df = portfolio_raw_df.copy()

print(f"📊 过滤后数据: {len(filtered_df)} 行")
print(f"📅 日期范围: {filtered_df['date'].min()} 至 {filtered_df['date'].max()}")

# 显示股票数据统计
print("\n📊 各股票数据统计:")
print(filtered_df.groupby("tic").count())

In [14]:
filtered_df.groupby("tic").count()

           date  open  high  low  close  volume  day
tic
000657.sz   189   189   189  189    189     189  189
002640.sz   189   189   189  189    189     189  189
002664.sz   189   189   189  189    189     189  189
002850.SZ   189   189   189  189    189     189  189
300182.sz   189   189   189  189    189     189  189
688200.SH   189   189   189  189    189     189  189

### Normalize Data

We normalize the data dividing the time series of each stock by its maximum value, so that the dataframe contains values between 0 and 1.

In [ ]:
portfolio_norm_df = GroupByScaler(by="tic", scaler=MaxAbsScaler).fit_transform(filtered_df)
portfolio_norm_df

/home/stock/projects/finstock/FinRL/finrl/meta/preprocessor/preprocessors.py:101: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75
 1.   0.   0.25 0.5  0.75 1.   0.   0.75 1.   0.   0.25 0.5  0.75 1.
 0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75
 0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75
 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5
 0.75 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.75 1.
 0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75
 1.   0.   0.25 0.5  0.75 1.   0.   0.   0.25 0.5  0.75 1.   0.   0.25
 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.
 0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.
 0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75
 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5
 0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.   0.   0.25 0.5  0.75 1.
 0.   0.25 0.5  0.75 1.   0.   0.25]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  X.loc[select_mask, self.columns] = self.scalers[value].transform(

,date,open,high,low,close,volume,tic,day
0,2022-02-07,0.770122,0.766212,0.755855,0.751728,0.220435,000657.sz,0.00
1,2022-02-07,0.647170,0.634234,0.638258,0.629630,0.129204,002640.sz,0.00
2,2022-02-07,0.907989,0.852209,0.913408,0.856848,0.040349,002664.sz,0.00
3,2022-02-07,0.982061,0.992617,0.973118,0.948001,0.221950,002850.SZ,0.00
4,2022-02-07,0.719498,0.708705,0.795973,0.771144,0.408817,300182.sz,0.00
...,...,...,...,...,...,...,...,...
1129,2024-11-05,0.569811,0.587387,0.562500,0.583333,0.478685,002640.sz,0.25
1130,2024-11-05,0.906336,0.835449,0.864246,0.850129,1.000000,002664.sz,0.25
1131,2024-11-05,0.652353,0.682405,0.661712,0.685001,0.658451,002850.SZ,0.25
1132,2024-11-05,0.632839,0.645089,0.743624,0.713930,0.263015,300182.sz,0.25
1133,2024-11-05,0.259478,0.269324,0.269450,0.267574,0.516850,688200.SH,0.25

In [16]:
df_portfolio = portfolio_norm_df[["date", "tic", "close", "high", "low",'volume']]

df_portfolio_train = df_portfolio[(df_portfolio["date"] >= "2019-01-01") & (df_portfolio["date"] <= "2025-01-29")]

df_portfolio_2025 = df_portfolio[(df_portfolio["date"] >= "2021-09-01") & (df_portfolio["date"] <= "2025-04-15")]

unique_dates = df_portfolio_2025['date'].drop_duplicates().sort_values().reset_index(drop=True)
print(unique_dates)

0      2022-02-07
1      2022-02-08
2      2022-02-09
3      2022-02-10
4      2022-02-11
          ...
184    2024-10-30
185    2024-10-31
186    2024-11-01
187    2024-11-04
188    2024-11-05
Name: date, Length: 189, dtype: object

### Instantiate Environment

Using the `PortfolioOptimizationEnv`, it's easy to instantiate a portfolio optimization environment for reinforcement learning agents. In the example below, we use the dataframe created before to start an environment.

In [17]:
features=["close", "high", "low",'volume']
environment = PortfolioOptimizationEnv(
        df_portfolio_train,
        initial_amount=100000,
        comission_fee_pct=0.0025,
        time_window=4,
        features=features,
        normalize_df=None
    )

### Instantiate Model

Now, we can instantiate the model using FinRL API. In this example, we are going to use the EIIE architecture introduced by Jiang et. al.

:exclamation: **Note:** Remember to set the architecture's `time_window` parameter with the same value of the environment's `time_window`.

In [21]:
# set PolicyGradient parameters
model_kwargs = {
    "lr": 0.01,
    "policy": EIIE,
}

# here, we can set EIIE's parameters
policy_kwargs = {
    "k_size": 3,
    "time_window": 4,
    "initial_features":len(features)
}

model = DRLAgent(environment).get_model("pg", device, model_kwargs, policy_kwargs)

model_name = "AFTER"
file_path = f"policy_EIIE_US_{model_name}.pt"
import os
import torch

# if market.lower() == "us":
#     if os.path.isfile(file_path):
#         model.train_policy.load_state_dict(torch.load(file_path))
#         print(f"成功加载模型参数：{file_path}")
#     else:
#         print(f"未找到模型文件: {file_path}，请确认路径或先进行保存。")
# elif market.lower() == "hk":
#     if os.path.isfile(file_path):
#         model.train_policy.load_state_dict(torch.load("policy_EIIE_HK.pt"))
#         print("成功加载模型参数：policy_EIIE_HK.pt")
#     else:
#         print(f"未找到模型文件: {file_path}，请确认路径或先进行保存。")
# elif market.lower() == "ch":
#     # model.train_policy.load_state_dict(torch.load("policy_EIIE_CH3.pt"))
#     # print("成功加载模型参数：policy_EIIE_CH3.pt")
# else:
#     raise ValueError("market 变量必须为 'us' 或 'hk'")

### Train Model

In [25]:
DRLAgent.train_model(model, episodes=600)

if market.lower() == "us":  
    torch.save(model.train_policy.state_dict(), "policy_EIIE_US_{}.pt".format(model_name))

elif market.lower() == "hk":
    torch.save(model.train_policy.state_dict(), "policy_EIIE_HK.pt")
elif market.lower() == "ch":
    torch.save(model.train_policy.state_dict(), "policy_EIIE_CH3.pt")
else:
    raise ValueError("market 变量必须为 'us' 或 'hk'")

  0%|          | 0/600 [00:00<?, ?it/s]

=================================
Initial portfolio value:100000
Final portfolio value: 392846.53125
Final accumulative portfolio value: 3.9284653663635254
Maximum DrawDown: -0.30667698727407655
Sharpe ratio: 2.7792933350894637
=================================

  0%|          | 1/600 [00:01<11:45,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 397294.8125
Final accumulative portfolio value: 3.9729480743408203
Maximum DrawDown: -0.3028695082396581
Sharpe ratio: 2.805202940851459
=================================

  0%|          | 2/600 [00:03<17:41,  1.77s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 396006.25
Final accumulative portfolio value: 3.9600625038146973
Maximum DrawDown: -0.29825361934271966
Sharpe ratio: 2.7954784975586677
=================================

  0%|          | 3/600 [00:04<14:54,  1.50s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 398630.1875
Final accumulative portfolio value: 3.986301898956299
Maximum DrawDown: -0.29528110217991965
Sharpe ratio: 2.799033078273241
=================================

  1%|          | 4/600 [00:05<13:36,  1.37s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 402404.0625
Final accumulative portfolio value: 4.024040699005127
Maximum DrawDown: -0.2883144136789739
Sharpe ratio: 2.8226450479543717
=================================

  1%|          | 5/600 [00:06<12:53,  1.30s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 403906.5
Final accumulative portfolio value: 4.039064884185791
Maximum DrawDown: -0.28195052097618434
Sharpe ratio: 2.828865323144144
=================================

  1%|          | 6/600 [00:08<12:27,  1.26s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 404489.75
Final accumulative portfolio value: 4.044897556304932
Maximum DrawDown: -0.27305334912671875
Sharpe ratio: 2.83402429191482
=================================

  1%|          | 7/600 [00:09<12:16,  1.24s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 407829.125
Final accumulative portfolio value: 4.078291416168213
Maximum DrawDown: -0.2776877188732456
Sharpe ratio: 2.840763009359591
=================================

  1%|▏         | 8/600 [00:10<13:05,  1.33s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 410254.59375
Final accumulative portfolio value: 4.102545738220215
Maximum DrawDown: -0.2573188332298897
Sharpe ratio: 2.8670643906282263
=================================

  2%|▏         | 9/600 [00:11<12:36,  1.28s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 413508.28125
Final accumulative portfolio value: 4.135082721710205
Maximum DrawDown: -0.26206931044203363
Sharpe ratio: 2.858948600183082
=================================

  2%|▏         | 10/600 [00:13<12:17,  1.25s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 419093.6875
Final accumulative portfolio value: 4.190937042236328
Maximum DrawDown: -0.2525273642363173
Sharpe ratio: 2.8871370228025603
=================================

  2%|▏         | 11/600 [00:14<12:03,  1.23s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 420735.3125
Final accumulative portfolio value: 4.207353115081787
Maximum DrawDown: -0.2421338595038064
Sharpe ratio: 2.8895244649035248
=================================

  2%|▏         | 12/600 [00:15<11:53,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 424829.375
Final accumulative portfolio value: 4.248293876647949
Maximum DrawDown: -0.25346852954820764
Sharpe ratio: 2.88807693536565
=================================

  2%|▏         | 13/600 [00:16<11:44,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 427113.46875
Final accumulative portfolio value: 4.271134853363037
Maximum DrawDown: -0.22367357661867138
Sharpe ratio: 2.9166693718436325
=================================

  2%|▏         | 14/600 [00:17<11:39,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 429632.28125
Final accumulative portfolio value: 4.296322822570801
Maximum DrawDown: -0.24782425417611165
Sharpe ratio: 2.8929997121125854
=================================

  2%|▎         | 15/600 [00:19<11:35,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 433817.53125
Final accumulative portfolio value: 4.338175296783447
Maximum DrawDown: -0.20949504989054557
Sharpe ratio: 2.941073923824884
=================================

  3%|▎         | 16/600 [00:20<12:30,  1.28s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 439645.90625
Final accumulative portfolio value: 4.396459102630615
Maximum DrawDown: -0.2267953068165527
Sharpe ratio: 2.9223839489651073
=================================

  3%|▎         | 17/600 [00:21<12:10,  1.25s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 445288.375
Final accumulative portfolio value: 4.452883720397949
Maximum DrawDown: -0.20868796770267017
Sharpe ratio: 2.97005603776197
=================================

  3%|▎         | 18/600 [00:22<11:57,  1.23s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 446307.28125
Final accumulative portfolio value: 4.463072776794434
Maximum DrawDown: -0.21759375263684488
Sharpe ratio: 2.938131853889995
=================================

  3%|▎         | 19/600 [00:24<11:47,  1.22s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 440833.09375
Final accumulative portfolio value: 4.408330917358398
Maximum DrawDown: -0.20744293703705352
Sharpe ratio: 2.955064899662325
=================================

  3%|▎         | 20/600 [00:25<11:40,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 426683.375
Final accumulative portfolio value: 4.266833782196045
Maximum DrawDown: -0.25565534244394583
Sharpe ratio: 2.8505110389088006
=================================

  4%|▎         | 21/600 [00:26<11:32,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 465190.125
Final accumulative portfolio value: 4.6519012451171875
Maximum DrawDown: -0.2075663993987923
Sharpe ratio: 3.0315850483407325
=================================

  4%|▎         | 22/600 [00:27<11:27,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 468895.3125
Final accumulative portfolio value: 4.688952922821045
Maximum DrawDown: -0.2074779578768522
Sharpe ratio: 2.998387819839772
=================================

  4%|▍         | 23/600 [00:28<11:24,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 468629.625
Final accumulative portfolio value: 4.686296463012695
Maximum DrawDown: -0.20842857515453428
Sharpe ratio: 2.9788896181385582
=================================

  4%|▍         | 24/600 [00:29<11:22,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 471330.90625
Final accumulative portfolio value: 4.713309288024902
Maximum DrawDown: -0.20804342232374995
Sharpe ratio: 3.0141941948411874
=================================

  4%|▍         | 25/600 [00:31<11:26,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 479958.15625
Final accumulative portfolio value: 4.799581527709961
Maximum DrawDown: -0.20791172532600666
Sharpe ratio: 2.9979469417042752
=================================

  4%|▍         | 26/600 [00:32<12:47,  1.34s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 492169.375
Final accumulative portfolio value: 4.921693801879883
Maximum DrawDown: -0.20755895740917918
Sharpe ratio: 3.058002224573096
=================================

  4%|▍         | 27/600 [00:34<12:16,  1.29s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 497378.90625
Final accumulative portfolio value: 4.973789215087891
Maximum DrawDown: -0.2067420600011649
Sharpe ratio: 3.051498868772135
=================================

  5%|▍         | 28/600 [00:35<11:54,  1.25s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 504052.96875
Final accumulative portfolio value: 5.040529727935791
Maximum DrawDown: -0.20595779368105194
Sharpe ratio: 3.076028965910115
=================================

  5%|▍         | 29/600 [00:36<11:38,  1.22s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 509093.03125
Final accumulative portfolio value: 5.090930461883545
Maximum DrawDown: -0.20490812480149778
Sharpe ratio: 3.0828432824960705
=================================

  5%|▌         | 30/600 [00:37<11:27,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 514289.25
Final accumulative portfolio value: 5.142892360687256
Maximum DrawDown: -0.20400770844643867
Sharpe ratio: 3.0949158575771185
=================================

  5%|▌         | 31/600 [00:38<11:19,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 518489.96875
Final accumulative portfolio value: 5.184899806976318
Maximum DrawDown: -0.20314997742895735
Sharpe ratio: 3.1032741683659073
=================================

  5%|▌         | 32/600 [00:39<11:13,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 523608.15625
Final accumulative portfolio value: 5.236081600189209
Maximum DrawDown: -0.20280371254732632
Sharpe ratio: 3.108723093098044
=================================

  6%|▌         | 33/600 [00:41<11:09,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 524275.90625
Final accumulative portfolio value: 5.2427592277526855
Maximum DrawDown: -0.20208313337738515
Sharpe ratio: 3.113584846414694
=================================

  6%|▌         | 34/600 [00:42<11:05,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 521623.875
Final accumulative portfolio value: 5.216238975524902
Maximum DrawDown: -0.20241006171976528
Sharpe ratio: 3.0907799625727685
=================================

  6%|▌         | 35/600 [00:43<11:02,  1.17s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 509809.53125
Final accumulative portfolio value: 5.098095417022705
Maximum DrawDown: -0.2012807885170368
Sharpe ratio: 3.072196469655964
=================================

  6%|▌         | 36/600 [00:44<11:00,  1.17s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 505155.09375
Final accumulative portfolio value: 5.05155086517334
Maximum DrawDown: -0.2016834770089725
Sharpe ratio: 3.0390902169833187
=================================

  6%|▌         | 37/600 [00:45<10:58,  1.17s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 521653.71875
Final accumulative portfolio value: 5.216536998748779
Maximum DrawDown: -0.20083281603861736
Sharpe ratio: 3.1063358225809234
=================================

  6%|▋         | 38/600 [00:46<10:57,  1.17s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 547210.625
Final accumulative portfolio value: 5.472106456756592
Maximum DrawDown: -0.19982532387270846
Sharpe ratio: 3.133338089218339
=================================

  6%|▋         | 39/600 [00:48<12:25,  1.33s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 553683.1875
Final accumulative portfolio value: 5.536831855773926
Maximum DrawDown: -0.20069945019415503
Sharpe ratio: 3.1697696130586035
=================================

  7%|▋         | 40/600 [00:49<11:57,  1.28s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 546078.8125
Final accumulative portfolio value: 5.460788249969482
Maximum DrawDown: -0.2000474146660608
Sharpe ratio: 3.149011929390556
=================================

  7%|▋         | 41/600 [00:50<11:38,  1.25s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 556342.4375
Final accumulative portfolio value: 5.563424587249756
Maximum DrawDown: -0.20062456790890515
Sharpe ratio: 3.1487563245645163
=================================

  7%|▋         | 42/600 [00:52<11:24,  1.23s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 569881.625
Final accumulative portfolio value: 5.698816299438477
Maximum DrawDown: -0.20120697834649193
Sharpe ratio: 3.198457175656865
=================================

  7%|▋         | 43/600 [00:53<11:14,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 560674.5625
Final accumulative portfolio value: 5.606745719909668
Maximum DrawDown: -0.20007111563912094
Sharpe ratio: 3.1664057219128234
=================================

  7%|▋         | 44/600 [00:54<11:06,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 564325.3125
Final accumulative portfolio value: 5.643253326416016
Maximum DrawDown: -0.2000467566089742
Sharpe ratio: 3.1612119186423224
=================================

  8%|▊         | 45/600 [00:55<11:00,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 580617.1875
Final accumulative portfolio value: 5.806171894073486
Maximum DrawDown: -0.1996260247016436
Sharpe ratio: 3.2203380141892772
=================================

  8%|▊         | 46/600 [00:56<10:58,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 571058.5625
Final accumulative portfolio value: 5.710585594177246
Maximum DrawDown: -0.19817259804634368
Sharpe ratio: 3.1834050136099834
=================================

  8%|▊         | 47/600 [00:57<10:53,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 573907.125
Final accumulative portfolio value: 5.739071369171143
Maximum DrawDown: -0.19861989506769973
Sharpe ratio: 3.1779485404227668
=================================

  8%|▊         | 48/600 [00:59<10:50,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 591285.75
Final accumulative portfolio value: 5.912857532501221
Maximum DrawDown: -0.1988054490121186
Sharpe ratio: 3.2361912459928375
=================================

  8%|▊         | 49/600 [01:00<10:47,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 579100.625
Final accumulative portfolio value: 5.791006088256836
Maximum DrawDown: -0.1976197938891805
Sharpe ratio: 3.1927899514223004
=================================

  8%|▊         | 50/600 [01:01<10:47,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 581399.6875
Final accumulative portfolio value: 5.8139967918396
Maximum DrawDown: -0.19810484774541004
Sharpe ratio: 3.185469455103889
=================================

  8%|▊         | 51/600 [01:02<10:47,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 600730.75
Final accumulative portfolio value: 6.007307529449463
Maximum DrawDown: -0.1980259382030931
Sharpe ratio: 3.2493054064755293
=================================

  9%|▊         | 52/600 [01:03<10:47,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 583045.5625
Final accumulative portfolio value: 5.830455780029297
Maximum DrawDown: -0.19621802700418045
Sharpe ratio: 3.19670023910399
=================================

  9%|▉         | 53/600 [01:05<10:45,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 586574.0
Final accumulative portfolio value: 5.865739822387695
Maximum DrawDown: -0.1966855235047853
Sharpe ratio: 3.1911375740765187
=================================

  9%|▉         | 54/600 [01:06<10:44,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 609354.25
Final accumulative portfolio value: 6.093542575836182
Maximum DrawDown: -0.19704776988410477
Sharpe ratio: 3.2640972655526714
=================================

  9%|▉         | 55/600 [01:08<12:29,  1.38s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 582377.25
Final accumulative portfolio value: 5.823772430419922
Maximum DrawDown: -0.19534411055844136
Sharpe ratio: 3.1900040988267033
=================================

  9%|▉         | 56/600 [01:09<11:56,  1.32s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 590217.375
Final accumulative portfolio value: 5.9021735191345215
Maximum DrawDown: -0.19620177123603688
Sharpe ratio: 3.1905036234573174
=================================

 10%|▉         | 57/600 [01:10<11:33,  1.28s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 614402.25
Final accumulative portfolio value: 6.144022464752197
Maximum DrawDown: -0.19699412987761156
Sharpe ratio: 3.2685047500928484
=================================

 10%|▉         | 58/600 [01:11<11:15,  1.25s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 581884.5625
Final accumulative portfolio value: 5.818845748901367
Maximum DrawDown: -0.19503289545834146
Sharpe ratio: 3.1845392342102135
=================================

 10%|▉         | 59/600 [01:12<11:03,  1.23s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 600512.25
Final accumulative portfolio value: 6.005122661590576
Maximum DrawDown: -0.1953203370164004
Sharpe ratio: 3.2049524772129114
=================================

 10%|█         | 60/600 [01:13<10:54,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 615910.3125
Final accumulative portfolio value: 6.159102916717529
Maximum DrawDown: -0.19614078227348886
Sharpe ratio: 3.264637415203417
=================================

 10%|█         | 61/600 [01:15<10:48,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 598825.0
Final accumulative portfolio value: 5.988249778747559
Maximum DrawDown: -0.19432633858326354
Sharpe ratio: 3.222878806503065
=================================

 10%|█         | 62/600 [01:16<10:44,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 615495.9375
Final accumulative portfolio value: 6.154959201812744
Maximum DrawDown: -0.1940902397330696
Sharpe ratio: 3.2349146254862062
=================================

 10%|█         | 63/600 [01:17<10:41,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 623026.875
Final accumulative portfolio value: 6.230268955230713
Maximum DrawDown: -0.19489929622447466
Sharpe ratio: 3.269478123570634
=================================

 11%|█         | 64/600 [01:18<10:37,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 620808.4375
Final accumulative portfolio value: 6.208084583282471
Maximum DrawDown: -0.19336166202697214
Sharpe ratio: 3.2671380180601823
=================================

 11%|█         | 65/600 [01:19<10:34,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 627801.8125
Final accumulative portfolio value: 6.278017997741699
Maximum DrawDown: -0.19249317081451656
Sharpe ratio: 3.2640279877645964
=================================

 11%|█         | 66/600 [01:21<10:33,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 631961.8125
Final accumulative portfolio value: 6.319618225097656
Maximum DrawDown: -0.1928473080459765
Sharpe ratio: 3.2809389425375164
=================================

 11%|█         | 67/600 [01:22<10:30,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 634483.6875
Final accumulative portfolio value: 6.344836711883545
Maximum DrawDown: -0.19196251278816434
Sharpe ratio: 3.2911787786728026
=================================

 11%|█▏        | 68/600 [01:23<10:29,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 635762.5
Final accumulative portfolio value: 6.3576250076293945
Maximum DrawDown: -0.1913427728017898
Sharpe ratio: 3.2840147298232427
=================================

 12%|█▏        | 69/600 [01:24<10:27,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 638910.875
Final accumulative portfolio value: 6.389108657836914
Maximum DrawDown: -0.1918732477147087
Sharpe ratio: 3.290497442334182
=================================

 12%|█▏        | 70/600 [01:25<10:26,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 642410.0
Final accumulative portfolio value: 6.424099922180176
Maximum DrawDown: -0.19188652814432772
Sharpe ratio: 3.301669054329999
=================================

 12%|█▏        | 71/600 [01:26<10:24,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 641842.625
Final accumulative portfolio value: 6.418426036834717
Maximum DrawDown: -0.1915565659125953
Sharpe ratio: 3.2947298496001034
=================================

 12%|█▏        | 72/600 [01:28<10:23,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 644796.6875
Final accumulative portfolio value: 6.447967052459717
Maximum DrawDown: -0.1918740420501619
Sharpe ratio: 3.297948963035133
=================================

 12%|█▏        | 73/600 [01:29<10:22,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 647906.125
Final accumulative portfolio value: 6.479061126708984
Maximum DrawDown: -0.19182159451031
Sharpe ratio: 3.308121143316949
=================================

 12%|█▏        | 74/600 [01:30<10:22,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 647759.0
Final accumulative portfolio value: 6.477590084075928
Maximum DrawDown: -0.19130477906794896
Sharpe ratio: 3.3042508825274917
=================================

 12%|█▎        | 75/600 [01:32<12:28,  1.43s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 650621.1875
Final accumulative portfolio value: 6.506211757659912
Maximum DrawDown: -0.19134511875812155
Sharpe ratio: 3.307445218351328
=================================

 13%|█▎        | 76/600 [01:33<11:48,  1.35s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 652955.25
Final accumulative portfolio value: 6.529552459716797
Maximum DrawDown: -0.1912221075321523
Sharpe ratio: 3.3147456854552044
=================================

 13%|█▎        | 77/600 [01:34<11:20,  1.30s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 653400.125
Final accumulative portfolio value: 6.534001350402832
Maximum DrawDown: -0.19081277971114485
Sharpe ratio: 3.31211482837585
=================================

 13%|█▎        | 78/600 [01:36<11:01,  1.27s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 655898.5
Final accumulative portfolio value: 6.558985233306885
Maximum DrawDown: -0.1908591202137645
Sharpe ratio: 3.314740419254921
=================================

 13%|█▎        | 79/600 [01:37<10:46,  1.24s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 657768.1875
Final accumulative portfolio value: 6.577682018280029
Maximum DrawDown: -0.19066848951138105
Sharpe ratio: 3.3199244535749712
=================================

 13%|█▎        | 80/600 [01:38<10:37,  1.23s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 658575.5
Final accumulative portfolio value: 6.585754871368408
Maximum DrawDown: -0.19020977595491617
Sharpe ratio: 3.3185135027311734
=================================

 14%|█▎        | 81/600 [01:39<10:28,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 660827.5625
Final accumulative portfolio value: 6.608275413513184
Maximum DrawDown: -0.1900739056399926
Sharpe ratio: 3.321424858380784
=================================

 14%|█▎        | 82/600 [01:40<10:22,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 662382.4375
Final accumulative portfolio value: 6.623824596405029
Maximum DrawDown: -0.189734646126274
Sharpe ratio: 3.325424472145104
=================================

 14%|█▍        | 83/600 [01:41<10:17,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 663542.1875
Final accumulative portfolio value: 6.6354217529296875
Maximum DrawDown: -0.1893324904125181
Sharpe ratio: 3.3250193381785773
=================================

 14%|█▍        | 84/600 [01:43<10:12,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 665588.5625
Final accumulative portfolio value: 6.655885696411133
Maximum DrawDown: -0.1892500463821173
Sharpe ratio: 3.3279896376764655
=================================

 14%|█▍        | 85/600 [01:44<10:09,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 666884.625
Final accumulative portfolio value: 6.668846130371094
Maximum DrawDown: -0.1890032926938714
Sharpe ratio: 3.330607361977493
=================================

 14%|█▍        | 86/600 [01:45<10:07,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 668144.5625
Final accumulative portfolio value: 6.681445598602295
Maximum DrawDown: -0.18875785875476758
Sharpe ratio: 3.3307031809831096
=================================

 14%|█▍        | 87/600 [01:46<10:06,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 669963.625
Final accumulative portfolio value: 6.699636459350586
Maximum DrawDown: -0.18869777219535222
Sharpe ratio: 3.333533730186937
=================================

 15%|█▍        | 88/600 [01:47<10:05,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 671111.9375
Final accumulative portfolio value: 6.711119174957275
Maximum DrawDown: -0.1884603404300349
Sharpe ratio: 3.3354679364694184
=================================

 15%|█▍        | 89/600 [01:48<10:05,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 672504.0
Final accumulative portfolio value: 6.725039958953857
Maximum DrawDown: -0.18827516124464483
Sharpe ratio: 3.3362936338449947
=================================

 15%|█▌        | 90/600 [01:50<10:06,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 674155.5
Final accumulative portfolio value: 6.741555213928223
Maximum DrawDown: -0.18820320693985526
Sharpe ratio: 3.3391193908592363
=================================

 15%|█▌        | 91/600 [01:51<10:04,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 675252.625
Final accumulative portfolio value: 6.75252628326416
Maximum DrawDown: -0.18801320864317272
Sharpe ratio: 3.340524610117719
=================================

 15%|█▌        | 92/600 [01:52<10:03,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 676710.5625
Final accumulative portfolio value: 6.767105579376221
Maximum DrawDown: -0.1879303258762215
Sharpe ratio: 3.3417884673680134
=================================

 16%|█▌        | 93/600 [01:53<10:01,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 678134.1875
Final accumulative portfolio value: 6.781342029571533
Maximum DrawDown: -0.18786887967008803
Sharpe ratio: 3.3442262718154643
=================================

 16%|█▌        | 94/600 [01:54<09:59,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 679234.3125
Final accumulative portfolio value: 6.7923431396484375
Maximum DrawDown: -0.1877174817823536
Sharpe ratio: 3.3452296936334958
=================================

 16%|█▌        | 95/600 [01:56<09:57,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 680668.75
Final accumulative portfolio value: 6.806687355041504
Maximum DrawDown: -0.18764916790732833
Sharpe ratio: 3.3468895890632835
=================================

 16%|█▌        | 96/600 [01:57<09:56,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 681925.0
Final accumulative portfolio value: 6.819250106811523
Maximum DrawDown: -0.18752621254074264
Sharpe ratio: 3.3489086725831934
=================================

 16%|█▌        | 97/600 [01:58<09:55,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 683093.375
Final accumulative portfolio value: 6.830933570861816
Maximum DrawDown: -0.18736700976850995
Sharpe ratio: 3.350005015439442
=================================

 16%|█▋        | 98/600 [01:59<09:55,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 684465.0625
Final accumulative portfolio value: 6.844650745391846
Maximum DrawDown: -0.18727658428163274
Sharpe ratio: 3.351833971711901
=================================

 16%|█▋        | 99/600 [02:01<12:25,  1.49s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 685618.5625
Final accumulative portfolio value: 6.856185436248779
Maximum DrawDown: -0.18712907472344564
Sharpe ratio: 3.353458109371129
=================================

 17%|█▋        | 100/600 [02:03<11:36,  1.39s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 686830.0
Final accumulative portfolio value: 6.868299961090088
Maximum DrawDown: -0.18699521397094476
Sharpe ratio: 3.354654546101605
=================================

 17%|█▋        | 101/600 [02:04<11:03,  1.33s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 688097.75
Final accumulative portfolio value: 6.880977630615234
Maximum DrawDown: -0.18689166247421085
Sharpe ratio: 3.3564319716792745
=================================

 17%|█▋        | 102/600 [02:05<10:40,  1.29s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 689199.1875
Final accumulative portfolio value: 6.891992092132568
Maximum DrawDown: -0.18673225551534522
Sharpe ratio: 3.357770578444992
=================================

 17%|█▋        | 103/600 [02:06<10:24,  1.26s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 690416.375
Final accumulative portfolio value: 6.904163837432861
Maximum DrawDown: -0.18660442614572048
Sharpe ratio: 3.3591383802933406
=================================

 17%|█▋        | 104/600 [02:07<10:12,  1.24s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 691590.8125
Final accumulative portfolio value: 6.915908336639404
Maximum DrawDown: -0.18646790500013666
Sharpe ratio: 3.360809543894663
=================================

 18%|█▊        | 105/600 [02:08<10:05,  1.22s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 692692.9375
Final accumulative portfolio value: 6.926929473876953
Maximum DrawDown: -0.1863074098079961
Sharpe ratio: 3.3620636870750147
=================================

 18%|█▊        | 106/600 [02:10<09:58,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 693885.5
Final accumulative portfolio value: 6.938855171203613
Maximum DrawDown: -0.18618397678645704
Sharpe ratio: 3.3635605589549478
=================================

 18%|█▊        | 107/600 [02:11<09:53,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 694986.875
Final accumulative portfolio value: 6.949868679046631
Maximum DrawDown: -0.18603910743236274
Sharpe ratio: 3.3650441071550183
=================================

 18%|█▊        | 108/600 [02:12<09:49,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 696095.0
Final accumulative portfolio value: 6.960949897766113
Maximum DrawDown: -0.18590119926951165
Sharpe ratio: 3.366293812947408
=================================

 18%|█▊        | 109/600 [02:13<09:46,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 697225.75
Final accumulative portfolio value: 6.972257614135742
Maximum DrawDown: -0.18578003147953193
Sharpe ratio: 3.367795739783363
=================================

 18%|█▊        | 110/600 [02:14<09:44,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 698297.875
Final accumulative portfolio value: 6.982978820800781
Maximum DrawDown: -0.18563843215023057
Sharpe ratio: 3.36912655179335
=================================

 18%|█▊        | 111/600 [02:16<09:41,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 699364.0625
Final accumulative portfolio value: 6.993640422821045
Maximum DrawDown: -0.18550398820040004
Sharpe ratio: 3.370448858716972
=================================

 19%|█▊        | 112/600 [02:17<09:41,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 700447.5
Final accumulative portfolio value: 7.004475116729736
Maximum DrawDown: -0.18538640659781958
Sharpe ratio: 3.371808906457641
=================================

 19%|█▉        | 113/600 [02:18<09:41,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 701502.8125
Final accumulative portfolio value: 7.01502799987793
Maximum DrawDown: -0.18526989476509081
Sharpe ratio: 3.3731819097494715
=================================

 19%|█▉        | 114/600 [02:19<09:42,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 702573.1875
Final accumulative portfolio value: 7.025732040405273
Maximum DrawDown: -0.1851579264038995
Sharpe ratio: 3.3744983422853827
=================================

 19%|█▉        | 115/600 [02:20<09:40,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 703580.6875
Final accumulative portfolio value: 7.035806655883789
Maximum DrawDown: -0.18502475415048247
Sharpe ratio: 3.375864054909052
=================================

 19%|█▉        | 116/600 [02:22<09:37,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 704652.375
Final accumulative portfolio value: 7.046523571014404
Maximum DrawDown: -0.18490935315624046
Sharpe ratio: 3.3770916400245667
=================================

 20%|█▉        | 117/600 [02:23<09:35,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 705671.8125
Final accumulative portfolio value: 7.056718349456787
Maximum DrawDown: -0.1847742289756764
Sharpe ratio: 3.378557914074225
=================================

 20%|█▉        | 118/600 [02:24<09:34,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 706665.4375
Final accumulative portfolio value: 7.066654205322266
Maximum DrawDown: -0.1846141789713146
Sharpe ratio: 3.3796841127217876
=================================

 20%|█▉        | 119/600 [02:25<09:33,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 707670.375
Final accumulative portfolio value: 7.0767035484313965
Maximum DrawDown: -0.18446721484326356
Sharpe ratio: 3.3810243377840536
=================================

 20%|██        | 120/600 [02:26<09:34,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 708662.75
Final accumulative portfolio value: 7.08662748336792
Maximum DrawDown: -0.18432225182448736
Sharpe ratio: 3.382245670815297
=================================

 20%|██        | 121/600 [02:28<09:38,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 709664.0
Final accumulative portfolio value: 7.096640110015869
Maximum DrawDown: -0.18419208725763558
Sharpe ratio: 3.383549900888316
=================================

 20%|██        | 122/600 [02:29<09:37,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 710663.1875
Final accumulative portfolio value: 7.106631755828857
Maximum DrawDown: -0.18405981625599532
Sharpe ratio: 3.384836610143815
=================================

 20%|██        | 123/600 [02:30<09:33,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 711652.125
Final accumulative portfolio value: 7.11652135848999
Maximum DrawDown: -0.18391293453901147
Sharpe ratio: 3.3861291720703215
=================================

 21%|██        | 124/600 [02:31<09:30,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 712594.5625
Final accumulative portfolio value: 7.125945568084717
Maximum DrawDown: -0.1837489700839503
Sharpe ratio: 3.3873441137605678
=================================

 21%|██        | 125/600 [02:32<09:27,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 713608.0625
Final accumulative portfolio value: 7.136080741882324
Maximum DrawDown: -0.18361127367113517
Sharpe ratio: 3.38856421105831
=================================

 21%|██        | 126/600 [02:34<09:25,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 714501.0
Final accumulative portfolio value: 7.145009994506836
Maximum DrawDown: -0.18343258236632543
Sharpe ratio: 3.3898802532135797
=================================

 21%|██        | 127/600 [02:35<09:23,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 715513.5
Final accumulative portfolio value: 7.155135154724121
Maximum DrawDown: -0.18329196490245903
Sharpe ratio: 3.3909494637065336
=================================

 21%|██▏       | 128/600 [02:36<09:23,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 716421.8125
Final accumulative portfolio value: 7.164217948913574
Maximum DrawDown: -0.18313197138567905
Sharpe ratio: 3.39243134300455
=================================

 22%|██▏       | 129/600 [02:38<12:16,  1.56s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 717411.1875
Final accumulative portfolio value: 7.174111843109131
Maximum DrawDown: -0.18298507551509657
Sharpe ratio: 3.3934313294734118
=================================

 22%|██▏       | 130/600 [02:40<11:21,  1.45s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 718304.25
Final accumulative portfolio value: 7.183042526245117
Maximum DrawDown: -0.18282349638838236
Sharpe ratio: 3.3949224789289443
=================================

 22%|██▏       | 131/600 [02:41<10:43,  1.37s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 719296.125
Final accumulative portfolio value: 7.1929612159729
Maximum DrawDown: -0.18267799347382108
Sharpe ratio: 3.3959100119086982
=================================

 22%|██▏       | 132/600 [02:42<10:15,  1.32s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 720159.4375
Final accumulative portfolio value: 7.201594352722168
Maximum DrawDown: -0.182506989163555
Sharpe ratio: 3.3974065302040777
=================================

 22%|██▏       | 133/600 [02:43<09:56,  1.28s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 721154.9375
Final accumulative portfolio value: 7.211549282073975
Maximum DrawDown: -0.1823657817733464
Sharpe ratio: 3.3983314973859904
=================================

 22%|██▏       | 134/600 [02:44<09:42,  1.25s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 721993.8125
Final accumulative portfolio value: 7.219938278198242
Maximum DrawDown: -0.18218868331808613
Sharpe ratio: 3.399888684402173
=================================

 22%|██▎       | 135/600 [02:45<09:32,  1.23s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 722988.1875
Final accumulative portfolio value: 7.229881763458252
Maximum DrawDown: -0.18204726123370796
Sharpe ratio: 3.400728652078158
=================================

 23%|██▎       | 136/600 [02:47<09:24,  1.22s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 723810.0625
Final accumulative portfolio value: 7.238100528717041
Maximum DrawDown: -0.1818668359288369
Sharpe ratio: 3.402360982608089
=================================

 23%|██▎       | 137/600 [02:48<09:20,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 724796.5
Final accumulative portfolio value: 7.247964859008789
Maximum DrawDown: -0.1817185790234398
Sharpe ratio: 3.4031267377814536
=================================

 23%|██▎       | 138/600 [02:49<09:15,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 725628.75
Final accumulative portfolio value: 7.256287574768066
Maximum DrawDown: -0.18154566306627173
Sharpe ratio: 3.4048277827024873
=================================

 23%|██▎       | 139/600 [02:50<09:12,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 726594.6875
Final accumulative portfolio value: 7.265946865081787
Maximum DrawDown: -0.18139388819666313
Sharpe ratio: 3.405566101298728
=================================

 23%|██▎       | 140/600 [02:51<09:09,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 727424.5
Final accumulative portfolio value: 7.274244785308838
Maximum DrawDown: -0.1812211719170007
Sharpe ratio: 3.4072611105012305
=================================

 24%|██▎       | 141/600 [02:53<09:07,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 728372.0625
Final accumulative portfolio value: 7.28372049331665
Maximum DrawDown: -0.18106850997146406
Sharpe ratio: 3.408014164547282
=================================

 24%|██▎       | 142/600 [02:54<09:05,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 729223.0625
Final accumulative portfolio value: 7.292230606079102
Maximum DrawDown: -0.18091961771041032
Sharpe ratio: 3.4096715576484646
=================================

 24%|██▍       | 143/600 [02:55<09:03,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 730140.9375
Final accumulative portfolio value: 7.3014092445373535
Maximum DrawDown: -0.18076486953829496
Sharpe ratio: 3.410507003686246
=================================

 24%|██▍       | 144/600 [02:56<09:01,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 730994.625
Final accumulative portfolio value: 7.309946060180664
Maximum DrawDown: -0.1806186913489869
Sharpe ratio: 3.4120425829583056
=================================

 24%|██▍       | 145/600 [02:57<09:00,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 731918.25
Final accumulative portfolio value: 7.319182395935059
Maximum DrawDown: -0.18046525342165032
Sharpe ratio: 3.41299518267204
=================================

 24%|██▍       | 146/600 [02:59<08:58,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 732710.0625
Final accumulative portfolio value: 7.32710075378418
Maximum DrawDown: -0.1802737160284923
Sharpe ratio: 3.414444031256658
=================================

 24%|██▍       | 147/600 [03:00<08:56,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 733722.6875
Final accumulative portfolio value: 7.337226867675781
Maximum DrawDown: -0.1801535891866819
Sharpe ratio: 3.415320305292103
=================================

 25%|██▍       | 148/600 [03:01<08:55,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 734109.75
Final accumulative portfolio value: 7.341097354888916
Maximum DrawDown: -0.17978631791477429
Sharpe ratio: 3.4168043521034783
=================================

 25%|██▍       | 149/600 [03:02<08:54,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 735221.5625
Final accumulative portfolio value: 7.352215766906738
Maximum DrawDown: -0.1797964797152085
Sharpe ratio: 3.416611850973261
=================================

 25%|██▌       | 150/600 [03:03<08:53,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 734989.6875
Final accumulative portfolio value: 7.3498969078063965
Maximum DrawDown: -0.1793600737356834
Sharpe ratio: 3.4186383090576005
=================================

 25%|██▌       | 151/600 [03:04<08:52,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 735737.0625
Final accumulative portfolio value: 7.357370853424072
Maximum DrawDown: -0.17961041458308047
Sharpe ratio: 3.415616311547509
=================================

 25%|██▌       | 152/600 [03:06<08:50,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 735095.4375
Final accumulative portfolio value: 7.350954532623291
Maximum DrawDown: -0.17921630500232466
Sharpe ratio: 3.419200494880984
=================================

 26%|██▌       | 153/600 [03:07<08:49,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 734772.5625
Final accumulative portfolio value: 7.3477253913879395
Maximum DrawDown: -0.17974346451059464
Sharpe ratio: 3.411564529638869
=================================

 26%|██▌       | 154/600 [03:08<08:48,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 735704.8125
Final accumulative portfolio value: 7.357048034667969
Maximum DrawDown: -0.17956391182293385
Sharpe ratio: 3.4200881474814646
=================================

 26%|██▌       | 155/600 [03:09<08:47,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 735037.625
Final accumulative portfolio value: 7.350376129150391
Maximum DrawDown: -0.17994560342780075
Sharpe ratio: 3.4101690106116465
=================================

 26%|██▌       | 156/600 [03:10<08:46,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 738282.25
Final accumulative portfolio value: 7.382822513580322
Maximum DrawDown: -0.17985841462028962
Sharpe ratio: 3.4232927946538214
=================================

 26%|██▌       | 157/600 [03:12<08:45,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 739120.875
Final accumulative portfolio value: 7.391208648681641
Maximum DrawDown: -0.17941717450270767
Sharpe ratio: 3.4175997944947936
=================================

 26%|██▋       | 158/600 [03:13<08:43,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 741465.6875
Final accumulative portfolio value: 7.414656639099121
Maximum DrawDown: -0.17907103048613127
Sharpe ratio: 3.4273469802431813
=================================

 26%|██▋       | 159/600 [03:14<08:41,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 742770.5
Final accumulative portfolio value: 7.427704811096191
Maximum DrawDown: -0.17818195477366205
Sharpe ratio: 3.4261312122005174
=================================

 27%|██▋       | 160/600 [03:15<08:40,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 743813.75
Final accumulative portfolio value: 7.438137531280518
Maximum DrawDown: -0.17767930730372938
Sharpe ratio: 3.431423954514129
=================================

 27%|██▋       | 161/600 [03:16<08:40,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 745110.0
Final accumulative portfolio value: 7.451099872589111
Maximum DrawDown: -0.1773830163554193
Sharpe ratio: 3.4311701661588394
=================================

 27%|██▋       | 162/600 [03:17<08:40,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 745125.5625
Final accumulative portfolio value: 7.451255798339844
Maximum DrawDown: -0.1771853599183243
Sharpe ratio: 3.4336096433419923
=================================

 27%|██▋       | 163/600 [03:19<08:39,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 745811.4375
Final accumulative portfolio value: 7.458114147186279
Maximum DrawDown: -0.1776906692465553
Sharpe ratio: 3.4304989029619306
=================================

 27%|██▋       | 164/600 [03:20<08:37,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 744904.375
Final accumulative portfolio value: 7.4490437507629395
Maximum DrawDown: -0.17754959233254974
Sharpe ratio: 3.4328437065205035
=================================

 28%|██▊       | 165/600 [03:21<08:37,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 743950.4375
Final accumulative portfolio value: 7.439504146575928
Maximum DrawDown: -0.17826949927543745
Sharpe ratio: 3.424374794529561
=================================

 28%|██▊       | 166/600 [03:24<11:54,  1.65s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 744402.9375
Final accumulative portfolio value: 7.444029331207275
Maximum DrawDown: -0.17793007957339557
Sharpe ratio: 3.4322000657685297
=================================

 28%|██▊       | 167/600 [03:25<10:53,  1.51s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 742828.0
Final accumulative portfolio value: 7.428279876708984
Maximum DrawDown: -0.1783752021202274
Sharpe ratio: 3.420451251372326
=================================

 28%|██▊       | 168/600 [03:26<10:09,  1.41s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 746781.25
Final accumulative portfolio value: 7.467812538146973
Maximum DrawDown: -0.17818302832742128
Sharpe ratio: 3.435661474960994
=================================

 28%|██▊       | 169/600 [03:27<09:40,  1.35s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 747135.6875
Final accumulative portfolio value: 7.4713568687438965
Maximum DrawDown: -0.17781649457569526
Sharpe ratio: 3.4281032721003033
=================================

 28%|██▊       | 170/600 [03:29<09:20,  1.30s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 750189.0625
Final accumulative portfolio value: 7.501890659332275
Maximum DrawDown: -0.1774568109099507
Sharpe ratio: 3.440031816609676
=================================

 28%|██▊       | 171/600 [03:30<09:05,  1.27s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 751370.4375
Final accumulative portfolio value: 7.513704299926758
Maximum DrawDown: -0.17651404328107767
Sharpe ratio: 3.4374135934270904
=================================

 29%|██▊       | 172/600 [03:31<08:54,  1.25s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 752572.5
Final accumulative portfolio value: 7.5257248878479
Maximum DrawDown: -0.175862099946412
Sharpe ratio: 3.444176291583515
=================================

 29%|██▉       | 173/600 [03:32<08:45,  1.23s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 753879.625
Final accumulative portfolio value: 7.538796424865723
Maximum DrawDown: -0.1754015300012598
Sharpe ratio: 3.4431258889464966
=================================

 29%|██▉       | 174/600 [03:33<08:37,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 754356.1875
Final accumulative portfolio value: 7.543561935424805
Maximum DrawDown: -0.17511850902521497
Sharpe ratio: 3.447356121458199
=================================

 29%|██▉       | 175/600 [03:34<08:32,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 755234.375
Final accumulative portfolio value: 7.552343845367432
Maximum DrawDown: -0.17534835489781597
Sharpe ratio: 3.4446430477071432
=================================

 29%|██▉       | 176/600 [03:36<08:27,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 754766.8125
Final accumulative portfolio value: 7.547667980194092
Maximum DrawDown: -0.1752842759133335
Sharpe ratio: 3.447408588009724
=================================

 30%|██▉       | 177/600 [03:37<08:24,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 754067.5
Final accumulative portfolio value: 7.540675163269043
Maximum DrawDown: -0.17596214764394913
Sharpe ratio: 3.4401977580952616
=================================

 30%|██▉       | 178/600 [03:38<08:25,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 753497.125
Final accumulative portfolio value: 7.534971237182617
Maximum DrawDown: -0.17559255580758903
Sharpe ratio: 3.445606655641674
=================================

 30%|██▉       | 179/600 [03:39<08:23,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 750481.5625
Final accumulative portfolio value: 7.504815578460693
Maximum DrawDown: -0.17637157046678065
Sharpe ratio: 3.431510114294132
=================================

 30%|███       | 180/600 [03:40<08:20,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 754471.5625
Final accumulative portfolio value: 7.544715404510498
Maximum DrawDown: -0.17618870675186438
Sharpe ratio: 3.4473188062047893
=================================

 30%|███       | 181/600 [03:42<08:19,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 753299.8125
Final accumulative portfolio value: 7.532998085021973
Maximum DrawDown: -0.17631207896275058
Sharpe ratio: 3.4355492803464545
=================================

 30%|███       | 182/600 [03:43<08:17,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 758460.125
Final accumulative portfolio value: 7.584601402282715
Maximum DrawDown: -0.17621882135758038
Sharpe ratio: 3.4521155126030325
=================================

 30%|███       | 183/600 [03:44<08:15,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 759472.1875
Final accumulative portfolio value: 7.594721794128418
Maximum DrawDown: -0.1750884026329792
Sharpe ratio: 3.4481818497753944
=================================

 31%|███       | 184/600 [03:45<08:13,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 761934.75
Final accumulative portfolio value: 7.61934757232666
Maximum DrawDown: -0.17447024179793513
Sharpe ratio: 3.4569333765561208
=================================

 31%|███       | 185/600 [03:46<08:11,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 762859.6875
Final accumulative portfolio value: 7.628596782684326
Maximum DrawDown: -0.1730064547163691
Sharpe ratio: 3.457952912119316
=================================

 31%|███       | 186/600 [03:48<08:09,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 764174.25
Final accumulative portfolio value: 7.641742706298828
Maximum DrawDown: -0.17273564061093238
Sharpe ratio: 3.4606568408513474
=================================

 31%|███       | 187/600 [03:49<08:08,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 764251.75
Final accumulative portfolio value: 7.642517566680908
Maximum DrawDown: -0.17229922791571584
Sharpe ratio: 3.462160831108254
=================================

 31%|███▏      | 188/600 [03:50<08:09,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 764731.125
Final accumulative portfolio value: 7.647311210632324
Maximum DrawDown: -0.17307899944290017
Sharpe ratio: 3.459263661843809
=================================

 32%|███▏      | 189/600 [03:51<08:08,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 763925.625
Final accumulative portfolio value: 7.639256477355957
Maximum DrawDown: -0.17314571244735555
Sharpe ratio: 3.4611874574534216
=================================

 32%|███▏      | 190/600 [03:52<08:07,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 762408.5
Final accumulative portfolio value: 7.624084949493408
Maximum DrawDown: -0.17412006513930922
Sharpe ratio: 3.4519736032181765
=================================

 32%|███▏      | 191/600 [03:53<08:07,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 762573.25
Final accumulative portfolio value: 7.625732421875
Maximum DrawDown: -0.17384944661776414
Sharpe ratio: 3.4589410639176466
=================================

 32%|███▏      | 192/600 [03:55<08:05,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 758973.125
Final accumulative portfolio value: 7.589731216430664
Maximum DrawDown: -0.17452028687899634
Sharpe ratio: 3.443823797453755
=================================

 32%|███▏      | 193/600 [03:56<08:02,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 765096.625
Final accumulative portfolio value: 7.650966167449951
Maximum DrawDown: -0.1742251503631539
Sharpe ratio: 3.4630607311612462
=================================

 32%|███▏      | 194/600 [03:57<08:02,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 765099.0625
Final accumulative portfolio value: 7.6509904861450195
Maximum DrawDown: -0.17354492696766288
Sharpe ratio: 3.4551007818514687
=================================

 32%|███▎      | 195/600 [03:58<08:01,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 768333.1875
Final accumulative portfolio value: 7.6833319664001465
Maximum DrawDown: -0.17305122707332998
Sharpe ratio: 3.4670086187295115
=================================

 33%|███▎      | 196/600 [03:59<07:59,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 769346.25
Final accumulative portfolio value: 7.693462371826172
Maximum DrawDown: -0.17200155304675502
Sharpe ratio: 3.4646037719807903
=================================

 33%|███▎      | 197/600 [04:01<07:58,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 770385.6875
Final accumulative portfolio value: 7.703856945037842
Maximum DrawDown: -0.17128960435683382
Sharpe ratio: 3.4711100135089703
=================================

 33%|███▎      | 198/600 [04:02<07:57,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 771210.25
Final accumulative portfolio value: 7.71210241317749
Maximum DrawDown: -0.171088431187849
Sharpe ratio: 3.468861334444748
=================================

 33%|███▎      | 199/600 [04:03<07:56,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 770365.5
Final accumulative portfolio value: 7.703654766082764
Maximum DrawDown: -0.170798027589657
Sharpe ratio: 3.472044691506478
=================================

 33%|███▎      | 200/600 [04:04<07:55,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 768086.875
Final accumulative portfolio value: 7.680868625640869
Maximum DrawDown: -0.17204700629714298
Sharpe ratio: 3.4609965735891772
=================================

 34%|███▎      | 201/600 [04:05<07:54,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 767719.0
Final accumulative portfolio value: 7.677189826965332
Maximum DrawDown: -0.17219042122858008
Sharpe ratio: 3.4676610361447406
=================================

 34%|███▎      | 202/600 [04:07<07:53,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 761094.0
Final accumulative portfolio value: 7.610939979553223
Maximum DrawDown: -0.17392103384999125
Sharpe ratio: 3.4448805772993847
=================================

 34%|███▍      | 203/600 [04:08<07:51,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 772581.5625
Final accumulative portfolio value: 7.725815773010254
Maximum DrawDown: -0.1745880670027924
Sharpe ratio: 3.473037690906001
=================================

 34%|███▍      | 204/600 [04:09<07:50,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 772538.0625
Final accumulative portfolio value: 7.7253804206848145
Maximum DrawDown: -0.17282436542397517
Sharpe ratio: 3.466780838546976
=================================

 34%|███▍      | 205/600 [04:10<07:53,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 775082.4375
Final accumulative portfolio value: 7.750824451446533
Maximum DrawDown: -0.172432656740806
Sharpe ratio: 3.473141571287236
=================================

 34%|███▍      | 206/600 [04:11<07:50,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 772757.0
Final accumulative portfolio value: 7.727570056915283
Maximum DrawDown: -0.16950300216463698
Sharpe ratio: 3.475286650951316
=================================

 34%|███▍      | 207/600 [04:13<07:48,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 767274.0625
Final accumulative portfolio value: 7.672740459442139
Maximum DrawDown: -0.1698201624430542
Sharpe ratio: 3.45967808949574
=================================

 35%|███▍      | 208/600 [04:14<07:46,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 768937.1875
Final accumulative portfolio value: 7.6893720626831055
Maximum DrawDown: -0.1693639287754407
Sharpe ratio: 3.473050074799443
=================================

 35%|███▍      | 209/600 [04:15<07:44,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 757921.3125
Final accumulative portfolio value: 7.5792131423950195
Maximum DrawDown: -0.17227762925744494
Sharpe ratio: 3.4375453581036486
=================================

 35%|███▌      | 210/600 [04:16<07:43,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 779766.375
Final accumulative portfolio value: 7.797663688659668
Maximum DrawDown: -0.17540133949860137
Sharpe ratio: 3.481703949031574
=================================

 35%|███▌      | 211/600 [04:19<11:23,  1.76s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 752627.875
Final accumulative portfolio value: 7.526278972625732
Maximum DrawDown: -0.17192688881148055
Sharpe ratio: 3.434761603468472
=================================

 35%|███▌      | 212/600 [04:20<10:16,  1.59s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 725000.25
Final accumulative portfolio value: 7.250002384185791
Maximum DrawDown: -0.17621917150617983
Sharpe ratio: 3.3695205514874638
=================================

 36%|███▌      | 213/600 [04:22<09:28,  1.47s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 737136.9375
Final accumulative portfolio value: 7.371369361877441
Maximum DrawDown: -0.180912706744907
Sharpe ratio: 3.4031839591262427
=================================

 36%|███▌      | 214/600 [04:23<08:54,  1.38s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 740960.6875
Final accumulative portfolio value: 7.40960693359375
Maximum DrawDown: -0.1750261687505762
Sharpe ratio: 3.4187481242728706
=================================

 36%|███▌      | 215/600 [04:24<08:30,  1.33s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 732988.625
Final accumulative portfolio value: 7.329886436462402
Maximum DrawDown: -0.17711917170752134
Sharpe ratio: 3.3789043261738496
=================================

 36%|███▌      | 216/600 [04:25<08:13,  1.29s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 717322.1875
Final accumulative portfolio value: 7.173222064971924
Maximum DrawDown: -0.1844813749581119
Sharpe ratio: 3.3617859678802873
=================================

 36%|███▌      | 217/600 [04:26<08:00,  1.26s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 770428.0625
Final accumulative portfolio value: 7.704280853271484
Maximum DrawDown: -0.18111469759574284
Sharpe ratio: 3.4559034738202166
=================================

 36%|███▋      | 218/600 [04:27<07:52,  1.24s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 656959.625
Final accumulative portfolio value: 6.569596290588379
Maximum DrawDown: -0.1820164750127481
Sharpe ratio: 3.2438894901932116
=================================

 36%|███▋      | 219/600 [04:29<07:44,  1.22s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 728081.6875
Final accumulative portfolio value: 7.280817031860352
Maximum DrawDown: -0.1703478424282433
Sharpe ratio: 3.3699886183057988
=================================

 37%|███▋      | 220/600 [04:30<07:38,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 633416.375
Final accumulative portfolio value: 6.334163665771484
Maximum DrawDown: -0.17931998918456615
Sharpe ratio: 3.273663962797187
=================================

 37%|███▋      | 221/600 [04:31<07:33,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 635180.3125
Final accumulative portfolio value: 6.351803302764893
Maximum DrawDown: -0.1691581990685852
Sharpe ratio: 3.218785143728148
=================================

 37%|███▋      | 222/600 [04:32<07:31,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 461924.875
Final accumulative portfolio value: 4.619248867034912
Maximum DrawDown: -0.21994277364392012
Sharpe ratio: 2.7117711229879
=================================

 37%|███▋      | 223/600 [04:33<07:31,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 498006.625
Final accumulative portfolio value: 4.980066299438477
Maximum DrawDown: -0.2178552123039894
Sharpe ratio: 2.8254830884008064
=================================

 37%|███▋      | 224/600 [04:35<07:28,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 739285.875
Final accumulative portfolio value: 7.392858982086182
Maximum DrawDown: -0.15806952674511443
Sharpe ratio: 3.392855037651454
=================================

 38%|███▊      | 225/600 [04:36<07:26,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 689606.5625
Final accumulative portfolio value: 6.896065711975098
Maximum DrawDown: -0.16752953518908653
Sharpe ratio: 3.338733074133995
=================================

 38%|███▊      | 226/600 [04:37<07:25,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 743142.3125
Final accumulative portfolio value: 7.431423187255859
Maximum DrawDown: -0.17399958270028182
Sharpe ratio: 3.4362480335155476
=================================

 38%|███▊      | 227/600 [04:38<07:24,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 708023.1875
Final accumulative portfolio value: 7.080231666564941
Maximum DrawDown: -0.17529216579297635
Sharpe ratio: 3.350626867092823
=================================

 38%|███▊      | 228/600 [04:39<07:21,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 735964.1875
Final accumulative portfolio value: 7.359642028808594
Maximum DrawDown: -0.18426580987366337
Sharpe ratio: 3.382769911326841
=================================

 38%|███▊      | 229/600 [04:41<07:20,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 721788.25
Final accumulative portfolio value: 7.2178826332092285
Maximum DrawDown: -0.19497123138234973
Sharpe ratio: 3.3545353101069537
=================================

 38%|███▊      | 230/600 [04:42<07:18,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 743596.0625
Final accumulative portfolio value: 7.43596076965332
Maximum DrawDown: -0.19378373669952975
Sharpe ratio: 3.4021472786364213
=================================

 38%|███▊      | 231/600 [04:43<07:18,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 770148.8125
Final accumulative portfolio value: 7.701488018035889
Maximum DrawDown: -0.18454241626224532
Sharpe ratio: 3.453979102453939
=================================

 39%|███▊      | 232/600 [04:44<07:18,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 717012.1875
Final accumulative portfolio value: 7.170121669769287
Maximum DrawDown: -0.17197980398560542
Sharpe ratio: 3.3640905388480657
=================================

 39%|███▉      | 233/600 [04:45<07:17,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 741447.625
Final accumulative portfolio value: 7.41447639465332
Maximum DrawDown: -0.17099659615882357
Sharpe ratio: 3.399432344802358
=================================

 39%|███▉      | 234/600 [04:46<07:15,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 698521.0625
Final accumulative portfolio value: 6.985210418701172
Maximum DrawDown: -0.17657868458041637
Sharpe ratio: 3.3391786656627422
=================================

 39%|███▉      | 235/600 [04:48<07:14,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 768274.4375
Final accumulative portfolio value: 7.68274450302124
Maximum DrawDown: -0.17674543609288884
Sharpe ratio: 3.4569287231721413
=================================

 39%|███▉      | 236/600 [04:49<07:12,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 720232.5
Final accumulative portfolio value: 7.202324867248535
Maximum DrawDown: -0.17245311749954384
Sharpe ratio: 3.374001404001924
=================================

 40%|███▉      | 237/600 [04:50<07:11,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 733978.4375
Final accumulative portfolio value: 7.339784145355225
Maximum DrawDown: -0.1765916320684019
Sharpe ratio: 3.376031903697018
=================================

 40%|███▉      | 238/600 [04:51<07:10,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 724936.5625
Final accumulative portfolio value: 7.24936580657959
Maximum DrawDown: -0.18596074665525386
Sharpe ratio: 3.365021298704222
=================================

 40%|███▉      | 239/600 [04:52<07:09,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 747454.5
Final accumulative portfolio value: 7.474545001983643
Maximum DrawDown: -0.18690005088230222
Sharpe ratio: 3.4090315544040366
=================================

 40%|████      | 240/600 [04:54<07:09,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 763951.4375
Final accumulative portfolio value: 7.639514446258545
Maximum DrawDown: -0.18156599763799985
Sharpe ratio: 3.438461724862038
=================================

 40%|████      | 241/600 [04:55<07:09,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 741548.0625
Final accumulative portfolio value: 7.415480613708496
Maximum DrawDown: -0.17347569429532617
Sharpe ratio: 3.401828089998984
=================================

 40%|████      | 242/600 [04:56<07:07,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 745624.9375
Final accumulative portfolio value: 7.456249237060547
Maximum DrawDown: -0.16756999861617228
Sharpe ratio: 3.4047549156841033
=================================

 40%|████      | 243/600 [04:57<07:05,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 763544.0
Final accumulative portfolio value: 7.635439872741699
Maximum DrawDown: -0.16468846073677224
Sharpe ratio: 3.440893141463445
=================================

 41%|████      | 244/600 [04:58<07:04,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 768802.0625
Final accumulative portfolio value: 7.688020706176758
Maximum DrawDown: -0.16233751391585416
Sharpe ratio: 3.4580916256628105
=================================

 41%|████      | 245/600 [05:00<07:03,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 778981.625
Final accumulative portfolio value: 7.789816379547119
Maximum DrawDown: -0.15947082711931582
Sharpe ratio: 3.483995167752758
=================================

 41%|████      | 246/600 [05:01<07:02,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 773357.625
Final accumulative portfolio value: 7.73357629776001
Maximum DrawDown: -0.15827496621791615
Sharpe ratio: 3.475549400006188
=================================

 41%|████      | 247/600 [05:02<07:01,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 777598.5625
Final accumulative portfolio value: 7.7759857177734375
Maximum DrawDown: -0.16342992827021663
Sharpe ratio: 3.4742127677123333
=================================

 41%|████▏     | 248/600 [05:03<06:59,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 784591.5625
Final accumulative portfolio value: 7.845915794372559
Maximum DrawDown: -0.17071328167552313
Sharpe ratio: 3.4869903055635585
=================================

 42%|████▏     | 249/600 [05:04<06:58,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 782868.25
Final accumulative portfolio value: 7.8286824226379395
Maximum DrawDown: -0.1729089160081736
Sharpe ratio: 3.4833340365099033
=================================

 42%|████▏     | 250/600 [05:06<06:56,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 780195.1875
Final accumulative portfolio value: 7.801951885223389
Maximum DrawDown: -0.17485302218226795
Sharpe ratio: 3.4723961610214245
=================================

 42%|████▏     | 251/600 [05:07<06:55,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 782062.1875
Final accumulative portfolio value: 7.820621967315674
Maximum DrawDown: -0.17701540098417845
Sharpe ratio: 3.4761835630618863
=================================

 42%|████▏     | 252/600 [05:08<06:53,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 787353.9375
Final accumulative portfolio value: 7.873539447784424
Maximum DrawDown: -0.175156348846905
Sharpe ratio: 3.487694710806582
=================================

 42%|████▏     | 253/600 [05:09<06:52,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 783708.6875
Final accumulative portfolio value: 7.8370866775512695
Maximum DrawDown: -0.1698518458730226
Sharpe ratio: 3.487148533693214
=================================

 42%|████▏     | 254/600 [05:10<06:50,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 790910.5
Final accumulative portfolio value: 7.909104824066162
Maximum DrawDown: -0.167514184359278
Sharpe ratio: 3.4969206994354183
=================================

 42%|████▎     | 255/600 [05:11<06:50,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 793825.5
Final accumulative portfolio value: 7.9382548332214355
Maximum DrawDown: -0.1668904201950423
Sharpe ratio: 3.5053058953365386
=================================

 43%|████▎     | 256/600 [05:13<06:48,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 786924.3125
Final accumulative portfolio value: 7.869243144989014
Maximum DrawDown: -0.1642657594715765
Sharpe ratio: 3.497339633689991
=================================

 43%|████▎     | 257/600 [05:14<06:47,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 787923.125
Final accumulative portfolio value: 7.8792314529418945
Maximum DrawDown: -0.16611530006685105
Sharpe ratio: 3.4908775171647317
=================================

 43%|████▎     | 258/600 [05:15<06:46,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 795167.5625
Final accumulative portfolio value: 7.9516754150390625
Maximum DrawDown: -0.1692384510077416
Sharpe ratio: 3.5041710710888987
=================================

 43%|████▎     | 259/600 [05:16<06:46,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 784960.25
Final accumulative portfolio value: 7.849602699279785
Maximum DrawDown: -0.16763790605698703
Sharpe ratio: 3.489983883740573
=================================

 43%|████▎     | 260/600 [05:17<06:44,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 786929.4375
Final accumulative portfolio value: 7.869294166564941
Maximum DrawDown: -0.1692184896845622
Sharpe ratio: 3.4839786523737732
=================================

 44%|████▎     | 261/600 [05:19<06:43,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 788692.1875
Final accumulative portfolio value: 7.8869218826293945
Maximum DrawDown: -0.1718290096177666
Sharpe ratio: 3.4883925616290368
=================================

 44%|████▎     | 262/600 [05:20<06:44,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 795584.75
Final accumulative portfolio value: 7.955847263336182
Maximum DrawDown: -0.16866031466634612
Sharpe ratio: 3.505266973487518
=================================

 44%|████▍     | 263/600 [05:21<06:43,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 793617.5625
Final accumulative portfolio value: 7.93617582321167
Maximum DrawDown: -0.16552813400669608
Sharpe ratio: 3.4998045499986725
=================================

 44%|████▍     | 264/600 [05:22<06:43,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 795637.75
Final accumulative portfolio value: 7.9563775062561035
Maximum DrawDown: -0.1653945470521918
Sharpe ratio: 3.502490759568451
=================================

 44%|████▍     | 265/600 [05:23<06:41,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 801819.875
Final accumulative portfolio value: 8.01819896697998
Maximum DrawDown: -0.16446770997282523
Sharpe ratio: 3.517380377150978
=================================

 44%|████▍     | 266/600 [05:25<06:39,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 793420.5625
Final accumulative portfolio value: 7.934205532073975
Maximum DrawDown: -0.16204688798877676
Sharpe ratio: 3.5074646687909783
=================================

 44%|████▍     | 267/600 [05:26<06:39,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 793402.0
Final accumulative portfolio value: 7.934020042419434
Maximum DrawDown: -0.1641276032185034
Sharpe ratio: 3.4997025785377076
=================================

 45%|████▍     | 268/600 [05:29<10:29,  1.90s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 801175.375
Final accumulative portfolio value: 8.011754035949707
Maximum DrawDown: -0.1674935552594814
Sharpe ratio: 3.5148342797581624
=================================

 45%|████▍     | 269/600 [05:31<09:18,  1.69s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 785822.3125
Final accumulative portfolio value: 7.858222961425781
Maximum DrawDown: -0.16640671122901796
Sharpe ratio: 3.492767195618593
=================================

 45%|████▌     | 270/600 [05:32<08:27,  1.54s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 783924.6875
Final accumulative portfolio value: 7.83924674987793
Maximum DrawDown: -0.169658633961424
Sharpe ratio: 3.47793480535617
=================================

 45%|████▌     | 271/600 [05:33<07:51,  1.43s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 788557.125
Final accumulative portfolio value: 7.885571479797363
Maximum DrawDown: -0.17387814905733467
Sharpe ratio: 3.487985270547932
=================================

 45%|████▌     | 272/600 [05:34<07:25,  1.36s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 788710.6875
Final accumulative portfolio value: 7.887106895446777
Maximum DrawDown: -0.17053673826075144
Sharpe ratio: 3.4946562546165603
=================================

 46%|████▌     | 273/600 [05:35<07:07,  1.31s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 794715.4375
Final accumulative portfolio value: 7.947154521942139
Maximum DrawDown: -0.16915734924427261
Sharpe ratio: 3.4965729749138146
=================================

 46%|████▌     | 274/600 [05:37<06:54,  1.27s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 796997.125
Final accumulative portfolio value: 7.969971179962158
Maximum DrawDown: -0.16956104146547768
Sharpe ratio: 3.503016087404466
=================================

 46%|████▌     | 275/600 [05:38<06:47,  1.25s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 803154.25
Final accumulative portfolio value: 8.031542778015137
Maximum DrawDown: -0.16554015070622086
Sharpe ratio: 3.5200252978883606
=================================

 46%|████▌     | 276/600 [05:39<06:39,  1.23s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 804098.3125
Final accumulative portfolio value: 8.040983200073242
Maximum DrawDown: -0.16248625667322847
Sharpe ratio: 3.520136396990557
=================================

 46%|████▌     | 277/600 [05:40<06:35,  1.22s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 804388.375
Final accumulative portfolio value: 8.043883323669434
Maximum DrawDown: -0.16281316298836623
Sharpe ratio: 3.519898170728975
=================================

 46%|████▋     | 278/600 [05:41<06:31,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 808227.875
Final accumulative portfolio value: 8.082279205322266
Maximum DrawDown: -0.1629204103933949
Sharpe ratio: 3.529105662394868
=================================

 46%|████▋     | 279/600 [05:42<06:28,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 805026.0625
Final accumulative portfolio value: 8.050260543823242
Maximum DrawDown: -0.16241963620066202
Sharpe ratio: 3.5238770863916
=================================

 47%|████▋     | 280/600 [05:44<06:25,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 805819.625
Final accumulative portfolio value: 8.058196067810059
Maximum DrawDown: -0.1643963771136383
Sharpe ratio: 3.520471817453143
=================================

 47%|████▋     | 281/600 [05:45<06:24,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 808412.1875
Final accumulative portfolio value: 8.084121704101562
Maximum DrawDown: -0.16636350870684746
Sharpe ratio: 3.525633877559151
=================================

 47%|████▋     | 282/600 [05:46<06:22,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 803312.6875
Final accumulative portfolio value: 8.033126831054688
Maximum DrawDown: -0.16543916581974238
Sharpe ratio: 3.5192786719372493
=================================

 47%|████▋     | 283/600 [05:47<06:21,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 805135.6875
Final accumulative portfolio value: 8.05135726928711
Maximum DrawDown: -0.1659214269828071
Sharpe ratio: 3.517755344351232
=================================

 47%|████▋     | 284/600 [05:48<06:18,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 808588.9375
Final accumulative portfolio value: 8.08588981628418
Maximum DrawDown: -0.16640250384339406
Sharpe ratio: 3.5257991560207267
=================================

 48%|████▊     | 285/600 [05:50<06:16,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 802498.6875
Final accumulative portfolio value: 8.02498722076416
Maximum DrawDown: -0.1639013246544263
Sharpe ratio: 3.5201171012535997
=================================

 48%|████▊     | 286/600 [05:51<06:14,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 803366.0625
Final accumulative portfolio value: 8.033660888671875
Maximum DrawDown: -0.16428341238396993
Sharpe ratio: 3.5153520407137173
=================================

 48%|████▊     | 287/600 [05:52<06:13,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 809742.9375
Final accumulative portfolio value: 8.097429275512695
Maximum DrawDown: -0.16546304838863612
Sharpe ratio: 3.528797299329852
=================================

 48%|████▊     | 288/600 [05:53<06:11,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 796573.0
Final accumulative portfolio value: 7.9657301902771
Maximum DrawDown: -0.16313866088266948
Sharpe ratio: 3.511670555576451
=================================

 48%|████▊     | 289/600 [05:54<06:11,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 791426.6875
Final accumulative portfolio value: 7.914267063140869
Maximum DrawDown: -0.16543173967894576
Sharpe ratio: 3.491456509358843
=================================

 48%|████▊     | 290/600 [05:56<06:09,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 801833.4375
Final accumulative portfolio value: 8.01833438873291
Maximum DrawDown: -0.16882666685323944
Sharpe ratio: 3.5123972374697696
=================================

 48%|████▊     | 291/600 [05:57<06:08,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 788771.875
Final accumulative portfolio value: 7.887718677520752
Maximum DrawDown: -0.16566116707284717
Sharpe ratio: 3.4973978377154107
=================================

 49%|████▊     | 292/600 [05:58<06:06,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 788621.25
Final accumulative portfolio value: 7.886212348937988
Maximum DrawDown: -0.1671258616513449
Sharpe ratio: 3.482967837891508
=================================

 49%|████▉     | 293/600 [05:59<06:04,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 790116.5
Final accumulative portfolio value: 7.901165008544922
Maximum DrawDown: -0.17064619245908097
Sharpe ratio: 3.488149211185576
=================================

 49%|████▉     | 294/600 [06:00<06:04,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 806483.6875
Final accumulative portfolio value: 8.064836502075195
Maximum DrawDown: -0.1666404644524282
Sharpe ratio: 3.5238950799520827
=================================

 49%|████▉     | 295/600 [06:02<06:03,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 800888.625
Final accumulative portfolio value: 8.008886337280273
Maximum DrawDown: -0.16304301266144272
Sharpe ratio: 3.510071734463207
=================================

 49%|████▉     | 296/600 [06:03<06:03,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 804046.9375
Final accumulative portfolio value: 8.0404691696167
Maximum DrawDown: -0.1630125587749509
Sharpe ratio: 3.5140981538143508
=================================

 50%|████▉     | 297/600 [06:04<06:02,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 812203.0
Final accumulative portfolio value: 8.122030258178711
Maximum DrawDown: -0.16202969813251855
Sharpe ratio: 3.5330871402411246
=================================

 50%|████▉     | 298/600 [06:05<06:00,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 800958.0
Final accumulative portfolio value: 8.0095796585083
Maximum DrawDown: -0.15881588547805037
Sharpe ratio: 3.5211705383590237
=================================

 50%|████▉     | 299/600 [06:06<05:58,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 800865.5
Final accumulative portfolio value: 8.008654594421387
Maximum DrawDown: -0.160831544238212
Sharpe ratio: 3.5102382895863764
=================================

 50%|█████     | 300/600 [06:08<05:58,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 807697.5625
Final accumulative portfolio value: 8.07697582244873
Maximum DrawDown: -0.1652664311019908
Sharpe ratio: 3.524050948373071
=================================

 50%|█████     | 301/600 [06:09<05:57,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 800123.3125
Final accumulative portfolio value: 8.001233100891113
Maximum DrawDown: -0.16432327986492978
Sharpe ratio: 3.5159445552131903
=================================

 50%|█████     | 302/600 [06:10<05:56,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 802327.4375
Final accumulative portfolio value: 8.023274421691895
Maximum DrawDown: -0.16632005255988092
Sharpe ratio: 3.5087379238946275
=================================

 50%|█████     | 303/600 [06:11<05:56,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 802524.6875
Final accumulative portfolio value: 8.025246620178223
Maximum DrawDown: -0.16944994406755276
Sharpe ratio: 3.510381492744514
=================================

 51%|█████     | 304/600 [06:12<05:53,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 811266.0625
Final accumulative portfolio value: 8.11266040802002
Maximum DrawDown: -0.16609010557695436
Sharpe ratio: 3.5308190529682153
=================================

 51%|█████     | 305/600 [06:14<05:52,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 811199.6875
Final accumulative portfolio value: 8.1119966506958
Maximum DrawDown: -0.16252133537801183
Sharpe ratio: 3.5288755188034817
=================================

 51%|█████     | 306/600 [06:15<05:51,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 812719.375
Final accumulative portfolio value: 8.127193450927734
Maximum DrawDown: -0.16173273639722996
Sharpe ratio: 3.5312666106185344
=================================

 51%|█████     | 307/600 [06:16<05:49,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 818076.375
Final accumulative portfolio value: 8.180764198303223
Maximum DrawDown: -0.16032129045053378
Sharpe ratio: 3.5447687506780494
=================================

 51%|█████▏    | 308/600 [06:17<05:49,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 809652.75
Final accumulative portfolio value: 8.096527099609375
Maximum DrawDown: -0.15802283569365438
Sharpe ratio: 3.5347045968139716
=================================

 52%|█████▏    | 309/600 [06:18<05:47,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 807354.0625
Final accumulative portfolio value: 8.073540687561035
Maximum DrawDown: -0.16019021273807765
Sharpe ratio: 3.522508817260578
=================================

 52%|█████▏    | 310/600 [06:19<05:45,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 815257.75
Final accumulative portfolio value: 8.15257740020752
Maximum DrawDown: -0.16369621363236653
Sharpe ratio: 3.5372234918732626
=================================

 52%|█████▏    | 311/600 [06:21<05:44,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 803838.875
Final accumulative portfolio value: 8.038389205932617
Maximum DrawDown: -0.1626975415852039
Sharpe ratio: 3.5220666642255685
=================================

 52%|█████▏    | 312/600 [06:22<05:42,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 804204.0625
Final accumulative portfolio value: 8.042040824890137
Maximum DrawDown: -0.16492122145431287
Sharpe ratio: 3.5117903433542135
=================================

 52%|█████▏    | 313/600 [06:23<05:41,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 805203.375
Final accumulative portfolio value: 8.052033424377441
Maximum DrawDown: -0.16806452407316108
Sharpe ratio: 3.5149523048629145
=================================

 52%|█████▏    | 314/600 [06:24<05:41,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 814462.4375
Final accumulative portfolio value: 8.144624710083008
Maximum DrawDown: -0.16465583036549902
Sharpe ratio: 3.5363657098203896
=================================

 52%|█████▎    | 315/600 [06:25<05:40,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 813632.5625
Final accumulative portfolio value: 8.13632583618164
Maximum DrawDown: -0.1613240252201541
Sharpe ratio: 3.532156255949915
=================================

 53%|█████▎    | 316/600 [06:27<05:39,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 816036.4375
Final accumulative portfolio value: 8.160364151000977
Maximum DrawDown: -0.1606148353547443
Sharpe ratio: 3.5361748693255692
=================================

 53%|█████▎    | 317/600 [06:28<05:37,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 821519.0
Final accumulative portfolio value: 8.215189933776855
Maximum DrawDown: -0.15918276103740137
Sharpe ratio: 3.5496982485343542
=================================

 53%|█████▎    | 318/600 [06:29<05:36,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 814366.375
Final accumulative portfolio value: 8.14366340637207
Maximum DrawDown: -0.15686711814631604
Sharpe ratio: 3.542045175305625
=================================

 53%|█████▎    | 319/600 [06:30<05:35,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 815538.625
Final accumulative portfolio value: 8.155385971069336
Maximum DrawDown: -0.15854397141630217
Sharpe ratio: 3.5366907109803294
=================================

 53%|█████▎    | 320/600 [06:31<05:34,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 820415.8125
Final accumulative portfolio value: 8.204157829284668
Maximum DrawDown: -0.16180160309057057
Sharpe ratio: 3.5458892230819212
=================================

 54%|█████▎    | 321/600 [06:33<05:33,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 812912.625
Final accumulative portfolio value: 8.12912654876709
Maximum DrawDown: -0.1613970545756649
Sharpe ratio: 3.5365175281861436
=================================

 54%|█████▎    | 322/600 [06:34<05:32,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 814574.875
Final accumulative portfolio value: 8.14574909210205
Maximum DrawDown: -0.16309850669703663
Sharpe ratio: 3.5311000305401516
=================================

 54%|█████▍    | 323/600 [06:35<05:31,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 816123.5625
Final accumulative portfolio value: 8.161235809326172
Maximum DrawDown: -0.16524533243145223
Sharpe ratio: 3.535055024494368
=================================

 54%|█████▍    | 324/600 [06:36<05:29,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 818000.0
Final accumulative portfolio value: 8.180000305175781
Maximum DrawDown: -0.16239849385397798
Sharpe ratio: 3.543351063713279
=================================

 54%|█████▍    | 325/600 [06:37<05:27,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 822035.3125
Final accumulative portfolio value: 8.220353126525879
Maximum DrawDown: -0.16037034230824287
Sharpe ratio: 3.546343863491222
=================================

 54%|█████▍    | 326/600 [06:39<05:26,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 823309.5625
Final accumulative portfolio value: 8.233095169067383
Maximum DrawDown: -0.15996378373717346
Sharpe ratio: 3.5501644984468865
=================================

 55%|█████▍    | 327/600 [06:40<05:25,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 824720.625
Final accumulative portfolio value: 8.247206687927246
Maximum DrawDown: -0.15820037997764824
Sharpe ratio: 3.556131391137658
=================================

 55%|█████▍    | 328/600 [06:41<05:24,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 825743.75
Final accumulative portfolio value: 8.257437705993652
Maximum DrawDown: -0.15729211566759316
Sharpe ratio: 3.5564265056433246
=================================

 55%|█████▍    | 329/600 [06:42<05:23,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 826248.4375
Final accumulative portfolio value: 8.262484550476074
Maximum DrawDown: -0.15810820046814988
Sharpe ratio: 3.5563473416095124
=================================

 55%|█████▌    | 330/600 [06:43<05:21,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 827118.25
Final accumulative portfolio value: 8.2711820602417
Maximum DrawDown: -0.15873093718626907
Sharpe ratio: 3.558341163845763
=================================

 55%|█████▌    | 331/600 [06:45<05:21,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 826371.5625
Final accumulative portfolio value: 8.263715744018555
Maximum DrawDown: -0.1590069258883089
Sharpe ratio: 3.556200564111961
=================================

 55%|█████▌    | 332/600 [06:46<05:19,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 826643.3125
Final accumulative portfolio value: 8.266432762145996
Maximum DrawDown: -0.1596946281031567
Sharpe ratio: 3.5552099984715
=================================

 56%|█████▌    | 333/600 [06:47<05:19,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 827479.0
Final accumulative portfolio value: 8.274789810180664
Maximum DrawDown: -0.1597820990282326
Sharpe ratio: 3.5574090912825334
=================================

 56%|█████▌    | 334/600 [06:48<05:18,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 827093.25
Final accumulative portfolio value: 8.2709321975708
Maximum DrawDown: -0.15890500941474384
Sharpe ratio: 3.5578094184923206
=================================

 56%|█████▌    | 335/600 [06:49<05:16,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 828146.125
Final accumulative portfolio value: 8.281461715698242
Maximum DrawDown: -0.15847629193354007
Sharpe ratio: 3.558730716583157
=================================

 56%|█████▌    | 336/600 [06:51<05:15,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 829037.0625
Final accumulative portfolio value: 8.29037094116211
Maximum DrawDown: -0.15826115730989399
Sharpe ratio: 3.5612271721733593
=================================

 56%|█████▌    | 337/600 [06:55<09:01,  2.06s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 828852.75
Final accumulative portfolio value: 8.288527488708496
Maximum DrawDown: -0.1577272197880759
Sharpe ratio: 3.5616677865948794
=================================

 56%|█████▋    | 338/600 [06:56<07:51,  1.80s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 829644.625
Final accumulative portfolio value: 8.296445846557617
Maximum DrawDown: -0.15789760055757907
Sharpe ratio: 3.5615542245002243
=================================

 56%|█████▋    | 339/600 [06:57<07:01,  1.62s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 830226.75
Final accumulative portfolio value: 8.302267074584961
Maximum DrawDown: -0.1582985007823453
Sharpe ratio: 3.5627700649479475
=================================

 57%|█████▋    | 340/600 [06:58<06:27,  1.49s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 829912.75
Final accumulative portfolio value: 8.299127578735352
Maximum DrawDown: -0.1581603790606203
Sharpe ratio: 3.5625011516858853
=================================

 57%|█████▋    | 341/600 [06:59<06:04,  1.41s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 830411.1875
Final accumulative portfolio value: 8.30411148071289
Maximum DrawDown: -0.1582484065004497
Sharpe ratio: 3.5622107072500793
=================================

 57%|█████▋    | 342/600 [07:01<05:46,  1.34s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 831030.875
Final accumulative portfolio value: 8.310308456420898
Maximum DrawDown: -0.15826876454010963
Sharpe ratio: 3.5637000971222594
=================================

 57%|█████▋    | 343/600 [07:02<05:33,  1.30s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 831029.5625
Final accumulative portfolio value: 8.310296058654785
Maximum DrawDown: -0.15774726337540645
Sharpe ratio: 3.564396044356533
=================================

 57%|█████▋    | 344/600 [07:03<05:30,  1.29s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 831670.0
Final accumulative portfolio value: 8.316699981689453
Maximum DrawDown: -0.15750154799591487
Sharpe ratio: 3.5648175217060656
=================================

 57%|█████▊    | 345/600 [07:04<05:21,  1.26s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 832285.4375
Final accumulative portfolio value: 8.322854042053223
Maximum DrawDown: -0.15744572000742363
Sharpe ratio: 3.566282408980975
=================================

 58%|█████▊    | 346/600 [07:05<05:14,  1.24s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 832368.25
Final accumulative portfolio value: 8.32368278503418
Maximum DrawDown: -0.15717640788611564
Sharpe ratio: 3.5668248647175687
=================================

 58%|█████▊    | 347/600 [07:07<05:09,  1.22s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 832841.875
Final accumulative portfolio value: 8.328418731689453
Maximum DrawDown: -0.1572251617456335
Sharpe ratio: 3.5668477648375077
=================================

 58%|█████▊    | 348/600 [07:08<05:05,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 833279.0
Final accumulative portfolio value: 8.33279037475586
Maximum DrawDown: -0.15739471818440254
Sharpe ratio: 3.567712916596293
=================================

 58%|█████▊    | 349/600 [07:09<05:02,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 833323.4375
Final accumulative portfolio value: 8.333234786987305
Maximum DrawDown: -0.15727528066023533
Sharpe ratio: 3.5679967331711757
=================================

 58%|█████▊    | 350/600 [07:10<04:59,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 833723.9375
Final accumulative portfolio value: 8.337239265441895
Maximum DrawDown: -0.15726355404266035
Sharpe ratio: 3.568124919272776
=================================

 58%|█████▊    | 351/600 [07:11<04:57,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 834170.9375
Final accumulative portfolio value: 8.34170913696289
Maximum DrawDown: -0.15724181027816508
Sharpe ratio: 3.5691300007549294
=================================

 59%|█████▊    | 352/600 [07:13<04:55,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 834350.375
Final accumulative portfolio value: 8.343503952026367
Maximum DrawDown: -0.15698541724170934
Sharpe ratio: 3.5697346335308238
=================================

 59%|█████▉    | 353/600 [07:14<04:53,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 834804.6875
Final accumulative portfolio value: 8.348047256469727
Maximum DrawDown: -0.15687008424484872
Sharpe ratio: 3.5701653024303748
=================================

 59%|█████▉    | 354/600 [07:15<04:52,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 835231.875
Final accumulative portfolio value: 8.35231876373291
Maximum DrawDown: -0.1568311633310252
Sharpe ratio: 3.571082318251366
=================================

 59%|█████▉    | 355/600 [07:16<04:51,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 835443.5
Final accumulative portfolio value: 8.354434967041016
Maximum DrawDown: -0.1566908234748986
Sharpe ratio: 3.5715588804230545
=================================

 59%|█████▉    | 356/600 [07:17<04:50,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 835822.875
Final accumulative portfolio value: 8.35822868347168
Maximum DrawDown: -0.1566780354555728
Sharpe ratio: 3.571853306223312
=================================

 60%|█████▉    | 357/600 [07:19<04:49,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 836176.75
Final accumulative portfolio value: 8.361767768859863
Maximum DrawDown: -0.15669294953354007
Sharpe ratio: 3.5725151982101844
=================================

 60%|█████▉    | 358/600 [07:20<04:48,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 836396.3125
Final accumulative portfolio value: 8.36396312713623
Maximum DrawDown: -0.15657730699753203
Sharpe ratio: 3.572956533959408
=================================

 60%|█████▉    | 359/600 [07:21<04:46,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 836755.0
Final accumulative portfolio value: 8.367549896240234
Maximum DrawDown: -0.15650953572597748
Sharpe ratio: 3.5733372160983596
=================================

 60%|██████    | 360/600 [07:22<04:45,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 837116.25
Final accumulative portfolio value: 8.371162414550781
Maximum DrawDown: -0.15643906177308298
Sharpe ratio: 3.5740621160324455
=================================

 60%|██████    | 361/600 [07:23<04:44,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 837389.875
Final accumulative portfolio value: 8.37389850616455
Maximum DrawDown: -0.15629067547911324
Sharpe ratio: 3.5746059662259464
=================================

 60%|██████    | 362/600 [07:24<04:44,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 837753.25
Final accumulative portfolio value: 8.377532958984375
Maximum DrawDown: -0.15620774356449374
Sharpe ratio: 3.575079370443995
=================================

 60%|██████    | 363/600 [07:26<04:42,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 838087.6875
Final accumulative portfolio value: 8.380876541137695
Maximum DrawDown: -0.1561495742290382
Sharpe ratio: 3.5757286700113884
=================================

 61%|██████    | 364/600 [07:27<04:41,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 838368.1875
Final accumulative portfolio value: 8.383682250976562
Maximum DrawDown: -0.1560713352981501
Sharpe ratio: 3.576178962048858
=================================

 61%|██████    | 365/600 [07:28<04:40,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 838698.25
Final accumulative portfolio value: 8.386982917785645
Maximum DrawDown: -0.1560374413109339
Sharpe ratio: 3.576623228551313
=================================

 61%|██████    | 366/600 [07:29<04:38,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 839004.3125
Final accumulative portfolio value: 8.390043258666992
Maximum DrawDown: -0.15598951693004748
Sharpe ratio: 3.5771789012171875
=================================

 61%|██████    | 367/600 [07:30<04:38,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 839289.375
Final accumulative portfolio value: 8.39289379119873
Maximum DrawDown: -0.15590578127081023
Sharpe ratio: 3.5776448710311093
=================================

 61%|██████▏   | 368/600 [07:32<04:36,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 839620.3125
Final accumulative portfolio value: 8.39620304107666
Maximum DrawDown: -0.1558404927814413
Sharpe ratio: 3.578138944133876
=================================

 62%|██████▏   | 369/600 [07:33<04:35,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 839934.4375
Final accumulative portfolio value: 8.399344444274902
Maximum DrawDown: -0.1557629561093148
Sharpe ratio: 3.5787163087185734
=================================

 62%|██████▏   | 370/600 [07:34<04:33,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 840233.5
Final accumulative portfolio value: 8.402335166931152
Maximum DrawDown: -0.15566911492840452
Sharpe ratio: 3.5792141071750776
=================================

 62%|██████▏   | 371/600 [07:35<04:32,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 840560.9375
Final accumulative portfolio value: 8.405609130859375
Maximum DrawDown: -0.15560310739322125
Sharpe ratio: 3.579713865809508
=================================

 62%|██████▏   | 372/600 [07:36<04:31,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 840856.5625
Final accumulative portfolio value: 8.408565521240234
Maximum DrawDown: -0.1555375260862224
Sharpe ratio: 3.58024994765803
=================================

 62%|██████▏   | 373/600 [07:38<04:30,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 841157.1875
Final accumulative portfolio value: 8.411571502685547
Maximum DrawDown: -0.1554802715593847
Sharpe ratio: 3.580688531275978
=================================

 62%|██████▏   | 374/600 [07:39<04:29,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 841464.25
Final accumulative portfolio value: 8.414642333984375
Maximum DrawDown: -0.15543248763799633
Sharpe ratio: 3.58119609476492
=================================

 62%|██████▎   | 375/600 [07:40<04:28,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 841756.875
Final accumulative portfolio value: 8.417569160461426
Maximum DrawDown: -0.15536616831871108
Sharpe ratio: 3.581684875669289
=================================

 63%|██████▎   | 376/600 [07:41<04:26,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 842061.3125
Final accumulative portfolio value: 8.420613288879395
Maximum DrawDown: -0.1552967037693619
Sharpe ratio: 3.5821691136859357
=================================

 63%|██████▎   | 377/600 [07:42<04:25,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 842370.375
Final accumulative portfolio value: 8.423704147338867
Maximum DrawDown: -0.15522347490654032
Sharpe ratio: 3.582690289331381
=================================

 63%|██████▎   | 378/600 [07:44<04:23,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 842664.1875
Final accumulative portfolio value: 8.426641464233398
Maximum DrawDown: -0.15514420737578516
Sharpe ratio: 3.583189259747929
=================================

 63%|██████▎   | 379/600 [07:45<04:22,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 842959.0625
Final accumulative portfolio value: 8.429590225219727
Maximum DrawDown: -0.15509223874629974
Sharpe ratio: 3.583660886291578
=================================

 63%|██████▎   | 380/600 [07:46<04:21,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 843248.1875
Final accumulative portfolio value: 8.43248176574707
Maximum DrawDown: -0.15508641823137703
Sharpe ratio: 3.584071074160378
=================================

 64%|██████▎   | 381/600 [07:47<04:20,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 843521.5
Final accumulative portfolio value: 8.43521499633789
Maximum DrawDown: -0.15508320598083225
Sharpe ratio: 3.5845078270606745
=================================

 64%|██████▎   | 382/600 [07:48<04:19,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 843791.1875
Final accumulative portfolio value: 8.437911987304688
Maximum DrawDown: -0.15505546981669083
Sharpe ratio: 3.5849370140971994
=================================

 64%|██████▍   | 383/600 [07:49<04:18,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 844083.6875
Final accumulative portfolio value: 8.440836906433105
Maximum DrawDown: -0.155008923056276
Sharpe ratio: 3.5854149317262847
=================================

 64%|██████▍   | 384/600 [07:51<04:16,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 844378.375
Final accumulative portfolio value: 8.4437837600708
Maximum DrawDown: -0.15493734258551017
Sharpe ratio: 3.585951965433648
=================================

 64%|██████▍   | 385/600 [07:52<04:15,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 844682.75
Final accumulative portfolio value: 8.44682788848877
Maximum DrawDown: -0.15485552815754022
Sharpe ratio: 3.586474480654453
=================================

 64%|██████▍   | 386/600 [07:53<04:15,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 844994.375
Final accumulative portfolio value: 8.449943542480469
Maximum DrawDown: -0.15478736420018202
Sharpe ratio: 3.5869981055799127
=================================

 64%|██████▍   | 387/600 [07:54<04:13,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 845292.25
Final accumulative portfolio value: 8.452922821044922
Maximum DrawDown: -0.15472721988744387
Sharpe ratio: 3.587495970264747
=================================

 65%|██████▍   | 388/600 [07:55<04:12,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 845589.0
Final accumulative portfolio value: 8.455889701843262
Maximum DrawDown: -0.15467600989025676
Sharpe ratio: 3.587953035808568
=================================

 65%|██████▍   | 389/600 [07:57<04:11,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 845884.0625
Final accumulative portfolio value: 8.458840370178223
Maximum DrawDown: -0.15462804918087514
Sharpe ratio: 3.5884137833788294
=================================

 65%|██████▌   | 390/600 [07:58<04:10,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 846167.5
Final accumulative portfolio value: 8.461674690246582
Maximum DrawDown: -0.15456543778260956
Sharpe ratio: 3.588877122006988
=================================

 65%|██████▌   | 391/600 [07:59<04:08,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 846454.0
Final accumulative portfolio value: 8.464539527893066
Maximum DrawDown: -0.15449948157151538
Sharpe ratio: 3.5893263714186348
=================================

 65%|██████▌   | 392/600 [08:00<04:07,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 846771.3125
Final accumulative portfolio value: 8.467713356018066
Maximum DrawDown: -0.15443528615768098
Sharpe ratio: 3.589806597386918
=================================

 66%|██████▌   | 393/600 [08:01<04:06,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 847031.8125
Final accumulative portfolio value: 8.470317840576172
Maximum DrawDown: -0.1543270206840356
Sharpe ratio: 3.5903827896670224
=================================

 66%|██████▌   | 394/600 [08:03<04:04,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 847344.5
Final accumulative portfolio value: 8.473444938659668
Maximum DrawDown: -0.15425071394420253
Sharpe ratio: 3.590780367624485
=================================

 66%|██████▌   | 395/600 [08:04<04:03,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 847651.8125
Final accumulative portfolio value: 8.476517677307129
Maximum DrawDown: -0.15422270576869224
Sharpe ratio: 3.591297895497279
=================================

 66%|██████▌   | 396/600 [08:05<04:02,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 847896.5625
Final accumulative portfolio value: 8.478965759277344
Maximum DrawDown: -0.15415947552801845
Sharpe ratio: 3.591749971757878
=================================

 66%|██████▌   | 397/600 [08:06<04:01,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 848221.625
Final accumulative portfolio value: 8.482215881347656
Maximum DrawDown: -0.15412199249697445
Sharpe ratio: 3.5921282393030536
=================================

 66%|██████▋   | 398/600 [08:07<04:00,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 848467.9375
Final accumulative portfolio value: 8.484679222106934
Maximum DrawDown: -0.1540394025957612
Sharpe ratio: 3.5927284751951896
=================================

 66%|██████▋   | 399/600 [08:09<03:58,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 848768.6875
Final accumulative portfolio value: 8.487687110900879
Maximum DrawDown: -0.15395591230667427
Sharpe ratio: 3.593086008381428
=================================

 67%|██████▋   | 400/600 [08:10<03:57,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 849083.6875
Final accumulative portfolio value: 8.490837097167969
Maximum DrawDown: -0.1539229776254546
Sharpe ratio: 3.593604601357999
=================================

 67%|██████▋   | 401/600 [08:11<03:56,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 849325.5625
Final accumulative portfolio value: 8.493255615234375
Maximum DrawDown: -0.15384019618371159
Sharpe ratio: 3.59409299492178
=================================

 67%|██████▋   | 402/600 [08:12<03:55,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 849654.625
Final accumulative portfolio value: 8.496545791625977
Maximum DrawDown: -0.15378476421240783
Sharpe ratio: 3.5944733061492795
=================================

 67%|██████▋   | 403/600 [08:13<03:53,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 849917.8125
Final accumulative portfolio value: 8.499177932739258
Maximum DrawDown: -0.15370665078385537
Sharpe ratio: 3.5950738059312553
=================================

 67%|██████▋   | 404/600 [08:14<03:52,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 850195.8125
Final accumulative portfolio value: 8.501957893371582
Maximum DrawDown: -0.15361767310434282
Sharpe ratio: 3.5954465751904494
=================================

 68%|██████▊   | 405/600 [08:16<03:52,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 850513.8125
Final accumulative portfolio value: 8.505138397216797
Maximum DrawDown: -0.15359063199624523
Sharpe ratio: 3.5959037821702164
=================================

 68%|██████▊   | 406/600 [08:17<03:50,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 850749.875
Final accumulative portfolio value: 8.507498741149902
Maximum DrawDown: -0.15352515538669453
Sharpe ratio: 3.596403487127634
=================================

 68%|██████▊   | 407/600 [08:18<03:48,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 851049.375
Final accumulative portfolio value: 8.510493278503418
Maximum DrawDown: -0.1534699561213353
Sharpe ratio: 3.5967611079056456
=================================

 68%|██████▊   | 408/600 [08:19<03:48,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 851331.0
Final accumulative portfolio value: 8.513310432434082
Maximum DrawDown: -0.15342329278896505
Sharpe ratio: 3.5972857948402344
=================================

 68%|██████▊   | 409/600 [08:20<03:46,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 851614.25
Final accumulative portfolio value: 8.516142845153809
Maximum DrawDown: -0.1533460114567614
Sharpe ratio: 3.5977301508086104
=================================

 68%|██████▊   | 410/600 [08:22<03:45,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 851885.0
Final accumulative portfolio value: 8.518850326538086
Maximum DrawDown: -0.1532570696329567
Sharpe ratio: 3.5982373146202877
=================================

 68%|██████▊   | 411/600 [08:23<03:44,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 852183.375
Final accumulative portfolio value: 8.521833419799805
Maximum DrawDown: -0.15319053011508088
Sharpe ratio: 3.5986695910800592
=================================

 69%|██████▊   | 412/600 [08:24<03:43,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 852465.8125
Final accumulative portfolio value: 8.524658203125
Maximum DrawDown: -0.15314030144693025
Sharpe ratio: 3.599147307589531
=================================

 69%|██████▉   | 413/600 [08:25<03:41,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 852726.875
Final accumulative portfolio value: 8.527268409729004
Maximum DrawDown: -0.15308012941453752
Sharpe ratio: 3.5995657847243896
=================================

 69%|██████▉   | 414/600 [08:26<03:40,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 853028.5625
Final accumulative portfolio value: 8.530285835266113
Maximum DrawDown: -0.15303281282108283
Sharpe ratio: 3.5999785454886113
=================================

 69%|██████▉   | 415/600 [08:28<03:39,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 853257.1875
Final accumulative portfolio value: 8.532571792602539
Maximum DrawDown: -0.15294447086318008
Sharpe ratio: 3.6004918364770617
=================================

 69%|██████▉   | 416/600 [08:29<03:38,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 853583.5625
Final accumulative portfolio value: 8.535835266113281
Maximum DrawDown: -0.1528808790404137
Sharpe ratio: 3.6008435074128093
=================================

 70%|██████▉   | 417/600 [08:30<03:37,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 853832.4375
Final accumulative portfolio value: 8.538324356079102
Maximum DrawDown: -0.1528078533473367
Sharpe ratio: 3.601436399940341
=================================

 70%|██████▉   | 418/600 [08:31<03:36,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 854109.8125
Final accumulative portfolio value: 8.541098594665527
Maximum DrawDown: -0.15273241480233513
Sharpe ratio: 3.6017763015754447
=================================

 70%|██████▉   | 419/600 [08:32<03:34,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 854401.0
Final accumulative portfolio value: 8.544010162353516
Maximum DrawDown: -0.1527116782499549
Sharpe ratio: 3.602233215518125
=================================

 70%|███████   | 420/600 [08:33<03:33,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 854626.1875
Final accumulative portfolio value: 8.54626178741455
Maximum DrawDown: -0.1526559595671878
Sharpe ratio: 3.602671248556793
=================================

 70%|███████   | 421/600 [08:35<03:31,  1.18s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 854921.4375
Final accumulative portfolio value: 8.549214363098145
Maximum DrawDown: -0.15261474548737142
Sharpe ratio: 3.603040035526196
=================================

 70%|███████   | 422/600 [08:39<06:40,  2.25s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 855183.75
Final accumulative portfolio value: 8.551837921142578
Maximum DrawDown: -0.15256352923567784
Sharpe ratio: 3.6035443887517484
=================================

 70%|███████   | 423/600 [08:41<05:41,  1.93s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 855439.0
Final accumulative portfolio value: 8.554389953613281
Maximum DrawDown: -0.15247505326988098
Sharpe ratio: 3.603975642920352
=================================

 71%|███████   | 424/600 [08:42<05:00,  1.71s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 855760.5625
Final accumulative portfolio value: 8.557605743408203
Maximum DrawDown: -0.15241742222040555
Sharpe ratio: 3.6044137942941488
=================================

 71%|███████   | 425/600 [08:43<04:31,  1.55s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 855978.9375
Final accumulative portfolio value: 8.559789657592773
Maximum DrawDown: -0.15231828498163835
Sharpe ratio: 3.6049650727735343
=================================

 71%|███████   | 426/600 [08:44<04:10,  1.44s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 856309.9375
Final accumulative portfolio value: 8.563098907470703
Maximum DrawDown: -0.15225545820877406
Sharpe ratio: 3.6052873911212955
=================================

 71%|███████   | 427/600 [08:45<03:57,  1.37s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 856549.75
Final accumulative portfolio value: 8.565497398376465
Maximum DrawDown: -0.15220637531787617
Sharpe ratio: 3.6058335454784367
=================================

 71%|███████▏  | 428/600 [08:46<03:46,  1.32s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 856808.5625
Final accumulative portfolio value: 8.568085670471191
Maximum DrawDown: -0.15214367417928942
Sharpe ratio: 3.606146877538991
=================================

 72%|███████▏  | 429/600 [08:48<03:38,  1.28s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 857098.8125
Final accumulative portfolio value: 8.570987701416016
Maximum DrawDown: -0.15212651123707832
Sharpe ratio: 3.6065595044127923
=================================

 72%|███████▏  | 430/600 [08:49<03:33,  1.26s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 857306.3125
Final accumulative portfolio value: 8.573062896728516
Maximum DrawDown: -0.1520543952596145
Sharpe ratio: 3.6070215165348776
=================================

 72%|███████▏  | 431/600 [08:50<03:28,  1.24s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 857607.375
Final accumulative portfolio value: 8.57607364654541
Maximum DrawDown: -0.15199587112694823
Sharpe ratio: 3.607375558720808
=================================

 72%|███████▏  | 432/600 [08:51<03:25,  1.22s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 857865.5
Final accumulative portfolio value: 8.578655242919922
Maximum DrawDown: -0.15194116964599735
Sharpe ratio: 3.607905273838511
=================================

 72%|███████▏  | 433/600 [08:52<03:22,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 858116.9375
Final accumulative portfolio value: 8.581169128417969
Maximum DrawDown: -0.1518618933979049
Sharpe ratio: 3.6083057519005197
=================================

 72%|███████▏  | 434/600 [08:54<03:20,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 858429.3125
Final accumulative portfolio value: 8.584293365478516
Maximum DrawDown: -0.15181674601544037
Sharpe ratio: 3.608740577060935
=================================

 72%|███████▎  | 435/600 [08:55<03:19,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 858615.125
Final accumulative portfolio value: 8.586151123046875
Maximum DrawDown: -0.15172539199209378
Sharpe ratio: 3.609241279929024
=================================

 73%|███████▎  | 436/600 [08:56<03:17,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 858955.75
Final accumulative portfolio value: 8.589557647705078
Maximum DrawDown: -0.15168259925035643
Sharpe ratio: 3.6095397295650637
=================================

 73%|███████▎  | 437/600 [08:57<03:15,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 859173.0
Final accumulative portfolio value: 8.591730117797852
Maximum DrawDown: -0.15163483051975069
Sharpe ratio: 3.6100999727249867
=================================

 73%|███████▎  | 438/600 [08:58<03:13,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 859433.25
Final accumulative portfolio value: 8.594332695007324
Maximum DrawDown: -0.1515675198589428
Sharpe ratio: 3.610386138538626
=================================

 73%|███████▎  | 439/600 [09:00<03:12,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 859725.5625
Final accumulative portfolio value: 8.59725570678711
Maximum DrawDown: -0.15155060752188687
Sharpe ratio: 3.6108158245729514
=================================

 73%|███████▎  | 440/600 [09:01<03:12,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 859921.125
Final accumulative portfolio value: 8.599211692810059
Maximum DrawDown: -0.15146809269941153
Sharpe ratio: 3.611273109544039
=================================

 74%|███████▎  | 441/600 [09:02<03:10,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 860245.0
Final accumulative portfolio value: 8.602450370788574
Maximum DrawDown: -0.15140456518159495
Sharpe ratio: 3.611617199630625
=================================

 74%|███████▎  | 442/600 [09:03<03:10,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 860462.9375
Final accumulative portfolio value: 8.604629516601562
Maximum DrawDown: -0.15132147598591816
Sharpe ratio: 3.612191383068235
=================================

 74%|███████▍  | 443/600 [09:04<03:08,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 860748.625
Final accumulative portfolio value: 8.607486724853516
Maximum DrawDown: -0.1512426812641272
Sharpe ratio: 3.6125212433577247
=================================

 74%|███████▍  | 444/600 [09:06<03:07,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 861032.9375
Final accumulative portfolio value: 8.610329627990723
Maximum DrawDown: -0.15122283916615575
Sharpe ratio: 3.6129810202479637
=================================

 74%|███████▍  | 445/600 [09:07<03:06,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 861233.125
Final accumulative portfolio value: 8.61233139038086
Maximum DrawDown: -0.15115686449328503
Sharpe ratio: 3.61338431136734
=================================

 74%|███████▍  | 446/600 [09:08<03:04,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 861542.625
Final accumulative portfolio value: 8.615426063537598
Maximum DrawDown: -0.15111585123196403
Sharpe ratio: 3.6137184717340207
=================================

 74%|███████▍  | 447/600 [09:09<03:03,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 861741.4375
Final accumulative portfolio value: 8.617414474487305
Maximum DrawDown: -0.15104050467011765
Sharpe ratio: 3.6142432965513103
=================================

 75%|███████▍  | 448/600 [09:10<03:01,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 862051.75
Final accumulative portfolio value: 8.62051773071289
Maximum DrawDown: -0.15097125277307544
Sharpe ratio: 3.614564632927952
=================================

 75%|███████▍  | 449/600 [09:12<03:00,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 862278.75
Final accumulative portfolio value: 8.622787475585938
Maximum DrawDown: -0.1509127319109378
Sharpe ratio: 3.615089972913947
=================================

 75%|███████▌  | 450/600 [09:13<02:58,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 862536.75
Final accumulative portfolio value: 8.625367164611816
Maximum DrawDown: -0.1508460661469897
Sharpe ratio: 3.615422685128693
=================================

 75%|███████▌  | 451/600 [09:14<02:57,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 862812.25
Final accumulative portfolio value: 8.628122329711914
Maximum DrawDown: -0.1508233590766932
Sharpe ratio: 3.615837147182602
=================================

 75%|███████▌  | 452/600 [09:15<02:56,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 863020.75
Final accumulative portfolio value: 8.630207061767578
Maximum DrawDown: -0.15076325193167017
Sharpe ratio: 3.6162542987114237
=================================

 76%|███████▌  | 453/600 [09:16<02:55,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 863297.9375
Final accumulative portfolio value: 8.632979393005371
Maximum DrawDown: -0.1507102736404673
Sharpe ratio: 3.6166049842757437
=================================

 76%|███████▌  | 454/600 [09:18<02:54,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 863549.8125
Final accumulative portfolio value: 8.635498046875
Maximum DrawDown: -0.15065799014250514
Sharpe ratio: 3.6170725472981022
=================================

 76%|███████▌  | 455/600 [09:19<02:52,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 863786.75
Final accumulative portfolio value: 8.63786792755127
Maximum DrawDown: -0.15058039094905384
Sharpe ratio: 3.6174699831816657
=================================

 76%|███████▌  | 456/600 [09:20<02:51,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 864082.4375
Final accumulative portfolio value: 8.640824317932129
Maximum DrawDown: -0.15052737466664945
Sharpe ratio: 3.6178728306458536
=================================

 76%|███████▌  | 457/600 [09:21<02:50,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 864275.75
Final accumulative portfolio value: 8.642757415771484
Maximum DrawDown: -0.15043864537160945
Sharpe ratio: 3.61835635471461
=================================

 76%|███████▋  | 458/600 [09:22<02:48,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 864588.8125
Final accumulative portfolio value: 8.645888328552246
Maximum DrawDown: -0.1503865523079574
Sharpe ratio: 3.6186577322965094
=================================

 76%|███████▋  | 459/600 [09:24<02:47,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 864796.375
Final accumulative portfolio value: 8.647963523864746
Maximum DrawDown: -0.15033583739604117
Sharpe ratio: 3.61917467553565
=================================

 77%|███████▋  | 460/600 [09:25<02:46,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 865057.9375
Final accumulative portfolio value: 8.650579452514648
Maximum DrawDown: -0.15028212434099408
Sharpe ratio: 3.6194556156217996
=================================

 77%|███████▋  | 461/600 [09:26<02:45,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 865315.75
Final accumulative portfolio value: 8.653157234191895
Maximum DrawDown: -0.15026452010155789
Sharpe ratio: 3.619874758582052
=================================

 77%|███████▋  | 462/600 [09:27<02:44,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 865523.1875
Final accumulative portfolio value: 8.655231475830078
Maximum DrawDown: -0.1501955451096204
Sharpe ratio: 3.6202791161119725
=================================

 77%|███████▋  | 463/600 [09:28<02:43,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 865814.375
Final accumulative portfolio value: 8.658143997192383
Maximum DrawDown: -0.15013807105640786
Sharpe ratio: 3.6206354487979295
=================================

 77%|███████▋  | 464/600 [09:29<02:42,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 866014.5625
Final accumulative portfolio value: 8.66014575958252
Maximum DrawDown: -0.15004683258037632
Sharpe ratio: 3.6211649989594794
=================================

 78%|███████▊  | 465/600 [09:31<02:40,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 866316.75
Final accumulative portfolio value: 8.663167953491211
Maximum DrawDown: -0.14998554667064423
Sharpe ratio: 3.6214621695414624
=================================

 78%|███████▊  | 466/600 [09:32<02:39,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 866529.875
Final accumulative portfolio value: 8.665298461914062
Maximum DrawDown: -0.14993292775801992
Sharpe ratio: 3.621984733049058
=================================

 78%|███████▊  | 467/600 [09:33<02:38,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 866783.5
Final accumulative portfolio value: 8.667835235595703
Maximum DrawDown: -0.1498822790087272
Sharpe ratio: 3.622258844631047
=================================

 78%|███████▊  | 468/600 [09:34<02:36,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 867039.5
Final accumulative portfolio value: 8.670394897460938
Maximum DrawDown: -0.1498702660249347
Sharpe ratio: 3.622661219138243
=================================

 78%|███████▊  | 469/600 [09:35<02:35,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 867239.75
Final accumulative portfolio value: 8.67239761352539
Maximum DrawDown: -0.1498032056401537
Sharpe ratio: 3.623056454274676
=================================

 78%|███████▊  | 470/600 [09:37<02:34,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 867516.1875
Final accumulative portfolio value: 8.675162315368652
Maximum DrawDown: -0.14974677350080368
Sharpe ratio: 3.6233981282577483
=================================

 78%|███████▊  | 471/600 [09:38<02:33,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 867752.1875
Final accumulative portfolio value: 8.677521705627441
Maximum DrawDown: -0.14968125524846176
Sharpe ratio: 3.623881042288913
=================================

 79%|███████▊  | 472/600 [09:39<02:32,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 867994.0625
Final accumulative portfolio value: 8.679940223693848
Maximum DrawDown: -0.14959824941169642
Sharpe ratio: 3.6242564484272854
=================================

 79%|███████▉  | 473/600 [09:40<02:31,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 868279.25
Final accumulative portfolio value: 8.682792663574219
Maximum DrawDown: -0.14955043268254298
Sharpe ratio: 3.6246555714471262
=================================

 79%|███████▉  | 474/600 [09:41<02:30,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 868451.9375
Final accumulative portfolio value: 8.68451976776123
Maximum DrawDown: -0.14946321863642975
Sharpe ratio: 3.62511064950636
=================================

 79%|███████▉  | 475/600 [09:43<02:29,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 868766.3125
Final accumulative portfolio value: 8.687663078308105
Maximum DrawDown: -0.14943110828165607
Sharpe ratio: 3.625363329345149
=================================

 79%|███████▉  | 476/600 [09:44<02:27,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 868947.5625
Final accumulative portfolio value: 8.689476013183594
Maximum DrawDown: -0.14938249771781997
Sharpe ratio: 3.625889890901029
=================================

 80%|███████▉  | 477/600 [09:45<02:27,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 869228.625
Final accumulative portfolio value: 8.692286491394043
Maximum DrawDown: -0.14932408463264102
Sharpe ratio: 3.6261320420420056
=================================

 80%|███████▉  | 478/600 [09:46<02:25,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 869456.75
Final accumulative portfolio value: 8.694567680358887
Maximum DrawDown: -0.1492782606884171
Sharpe ratio: 3.6266288162301783
=================================

 80%|███████▉  | 479/600 [09:47<02:24,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 869684.0
Final accumulative portfolio value: 8.696840286254883
Maximum DrawDown: -0.14919836992329705
Sharpe ratio: 3.6269682006129673
=================================

 80%|████████  | 480/600 [09:49<02:23,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 869956.1875
Final accumulative portfolio value: 8.699562072753906
Maximum DrawDown: -0.14916070633668166
Sharpe ratio: 3.627350504687181
=================================

 80%|████████  | 481/600 [09:50<02:22,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 870160.3125
Final accumulative portfolio value: 8.701602935791016
Maximum DrawDown: -0.1490961485565303
Sharpe ratio: 3.627787342638299
=================================

 80%|████████  | 482/600 [09:51<02:21,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 870422.0625
Final accumulative portfolio value: 8.70422077178955
Maximum DrawDown: -0.14903932460632074
Sharpe ratio: 3.6281130358319773
=================================

 80%|████████  | 483/600 [09:52<02:20,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 870660.4375
Final accumulative portfolio value: 8.70660400390625
Maximum DrawDown: -0.14899715204722408
Sharpe ratio: 3.6285429098632194
=================================

 81%|████████  | 484/600 [09:53<02:19,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 870878.75
Final accumulative portfolio value: 8.70878791809082
Maximum DrawDown: -0.1489301448903636
Sharpe ratio: 3.6289083612025355
=================================

 81%|████████  | 485/600 [09:55<02:18,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 871155.9375
Final accumulative portfolio value: 8.711559295654297
Maximum DrawDown: -0.14888450211498705
Sharpe ratio: 3.629274212519693
=================================

 81%|████████  | 486/600 [09:56<02:16,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 871326.8125
Final accumulative portfolio value: 8.713268280029297
Maximum DrawDown: -0.14879924921350463
Sharpe ratio: 3.6297239525443428
=================================

 81%|████████  | 487/600 [09:57<02:15,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 871639.9375
Final accumulative portfolio value: 8.716399192810059
Maximum DrawDown: -0.14875350134734355
Sharpe ratio: 3.63000793759413
=================================

 81%|████████▏ | 488/600 [09:58<02:13,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 871811.375
Final accumulative portfolio value: 8.718113899230957
Maximum DrawDown: -0.14869610579829462
Sharpe ratio: 3.6305131031463276
=================================

 82%|████████▏ | 489/600 [09:59<02:13,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 872103.75
Final accumulative portfolio value: 8.721037864685059
Maximum DrawDown: -0.14864049994270234
Sharpe ratio: 3.630770802221072
=================================

 82%|████████▏ | 490/600 [10:01<02:12,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 872316.0625
Final accumulative portfolio value: 8.723160743713379
Maximum DrawDown: -0.14859521138093967
Sharpe ratio: 3.631252280796973
=================================

 82%|████████▏ | 491/600 [10:02<02:10,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 872543.625
Final accumulative portfolio value: 8.725436210632324
Maximum DrawDown: -0.14851852936953092
Sharpe ratio: 3.631566564497304
=================================

 82%|████████▏ | 492/600 [10:03<02:09,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 872812.8125
Final accumulative portfolio value: 8.728128433227539
Maximum DrawDown: -0.14848603586515363
Sharpe ratio: 3.63194461181625
=================================

 82%|████████▏ | 493/600 [10:04<02:08,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 873002.9375
Final accumulative portfolio value: 8.730029106140137
Maximum DrawDown: -0.14841868196211094
Sharpe ratio: 3.6323626442164723
=================================

 82%|████████▏ | 494/600 [10:05<02:06,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 873271.4375
Final accumulative portfolio value: 8.732714653015137
Maximum DrawDown: -0.14836158510747532
Sharpe ratio: 3.632684251074229
=================================

 82%|████████▎ | 495/600 [10:07<02:05,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 873497.4375
Final accumulative portfolio value: 8.734973907470703
Maximum DrawDown: -0.14831359494593166
Sharpe ratio: 3.6331220417102785
=================================

 83%|████████▎ | 496/600 [10:08<02:03,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 873718.875
Final accumulative portfolio value: 8.737188339233398
Maximum DrawDown: -0.1482429552206922
Sharpe ratio: 3.633472411087469
=================================

 83%|████████▎ | 497/600 [10:09<02:02,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 873992.125
Final accumulative portfolio value: 8.739921569824219
Maximum DrawDown: -0.14819955785842143
Sharpe ratio: 3.6338437637141707
=================================

 83%|████████▎ | 498/600 [10:10<02:01,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 874149.625
Final accumulative portfolio value: 8.741496086120605
Maximum DrawDown: -0.14811413552740138
Sharpe ratio: 3.6342739022075063
=================================

 83%|████████▎ | 499/600 [10:11<02:00,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 874466.8125
Final accumulative portfolio value: 8.744668006896973
Maximum DrawDown: -0.14807729359855426
Sharpe ratio: 3.634543745312316
=================================

 83%|████████▎ | 500/600 [10:13<01:59,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 874618.3125
Final accumulative portfolio value: 8.746183395385742
Maximum DrawDown: -0.1480198526836365
Sharpe ratio: 3.6350410489176714
=================================

 84%|████████▎ | 501/600 [10:14<01:58,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 874917.1875
Final accumulative portfolio value: 8.74917221069336
Maximum DrawDown: -0.1479662359312618
Sharpe ratio: 3.6352807473129722
=================================

 84%|████████▎ | 502/600 [10:15<01:57,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 875115.0625
Final accumulative portfolio value: 8.751151084899902
Maximum DrawDown: -0.14792014205075166
Sharpe ratio: 3.6357711822108776
=================================

 84%|████████▍ | 503/600 [10:16<01:56,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 875350.875
Final accumulative portfolio value: 8.753508567810059
Maximum DrawDown: -0.147845174992829
Sharpe ratio: 3.6360677415284637
=================================

 84%|████████▍ | 504/600 [10:17<01:54,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 875608.125
Final accumulative portfolio value: 8.756081581115723
Maximum DrawDown: -0.14781113025254533
Sharpe ratio: 3.6364577723846967
=================================

 84%|████████▍ | 505/600 [10:18<01:53,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 875793.1875
Final accumulative portfolio value: 8.75793170928955
Maximum DrawDown: -0.14773870317389937
Sharpe ratio: 3.636855933590307
=================================

 84%|████████▍ | 506/600 [10:20<01:51,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 876081.9375
Final accumulative portfolio value: 8.760819435119629
Maximum DrawDown: -0.14768536355143969
Sharpe ratio: 3.6371783943841085
=================================

 84%|████████▍ | 507/600 [10:21<01:51,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 876254.125
Final accumulative portfolio value: 8.762540817260742
Maximum DrawDown: -0.14760759496869236
Sharpe ratio: 3.6376474475709157
=================================

 85%|████████▍ | 508/600 [10:22<01:50,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 876550.75
Final accumulative portfolio value: 8.765507698059082
Maximum DrawDown: -0.14755109351075646
Sharpe ratio: 3.6379272807572955
=================================

 85%|████████▍ | 509/600 [10:23<01:49,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 876731.3125
Final accumulative portfolio value: 8.767313003540039
Maximum DrawDown: -0.14749716811355407
Sharpe ratio: 3.6383946569456684
=================================

 85%|████████▌ | 510/600 [10:24<01:47,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 876986.8125
Final accumulative portfolio value: 8.769867897033691
Maximum DrawDown: -0.14744167065379532
Sharpe ratio: 3.638663105797122
=================================

 85%|████████▌ | 511/600 [10:26<01:46,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 877216.8125
Final accumulative portfolio value: 8.772168159484863
Maximum DrawDown: -0.1474151394491302
Sharpe ratio: 3.6390615518804164
=================================

 85%|████████▌ | 512/600 [10:27<01:45,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 877408.25
Final accumulative portfolio value: 8.77408218383789
Maximum DrawDown: -0.14734378677786863
Sharpe ratio: 3.6394153032946104
=================================

 86%|████████▌ | 513/600 [10:28<01:43,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 877679.375
Final accumulative portfolio value: 8.776793479919434
Maximum DrawDown: -0.14737138031238362
Sharpe ratio: 3.639759062503026
=================================

 86%|████████▌ | 514/600 [10:29<01:42,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 877872.0
Final accumulative portfolio value: 8.778719902038574
Maximum DrawDown: -0.14731676771183844
Sharpe ratio: 3.6401889581340225
=================================

 86%|████████▌ | 515/600 [10:30<01:41,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 878141.75
Final accumulative portfolio value: 8.781417846679688
Maximum DrawDown: -0.14737279525743197
Sharpe ratio: 3.6405246592914824
=================================

 86%|████████▌ | 516/600 [10:32<01:40,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 878338.8125
Final accumulative portfolio value: 8.783388137817383
Maximum DrawDown: -0.14731312954011988
Sharpe ratio: 3.640958775244445
=================================

 86%|████████▌ | 517/600 [10:33<01:39,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 878607.3125
Final accumulative portfolio value: 8.786072731018066
Maximum DrawDown: -0.14737260166238964
Sharpe ratio: 3.641269372667736
=================================

 86%|████████▋ | 518/600 [10:34<01:37,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 878792.0625
Final accumulative portfolio value: 8.787920951843262
Maximum DrawDown: -0.14730432018174444
Sharpe ratio: 3.641684842531542
=================================

 86%|████████▋ | 519/600 [10:35<01:37,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 879063.125
Final accumulative portfolio value: 8.790631294250488
Maximum DrawDown: -0.14737999711568361
Sharpe ratio: 3.641964839544083
=================================

 87%|████████▋ | 520/600 [10:36<01:35,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 879225.1875
Final accumulative portfolio value: 8.792251586914062
Maximum DrawDown: -0.14729460620856383
Sharpe ratio: 3.642382442953051
=================================

 87%|████████▋ | 521/600 [10:38<01:34,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 879499.1875
Final accumulative portfolio value: 8.794991493225098
Maximum DrawDown: -0.14737449918234802
Sharpe ratio: 3.6426630927821444
=================================

 87%|████████▋ | 522/600 [10:39<01:33,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 879700.875
Final accumulative portfolio value: 8.797008514404297
Maximum DrawDown: -0.14733105596615326
Sharpe ratio: 3.643093617144129
=================================

 87%|████████▋ | 523/600 [10:40<01:32,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 879920.125
Final accumulative portfolio value: 8.799201011657715
Maximum DrawDown: -0.1473380845171146
Sharpe ratio: 3.643423630258363
=================================

 87%|████████▋ | 524/600 [10:41<01:30,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 880172.75
Final accumulative portfolio value: 8.801727294921875
Maximum DrawDown: -0.14736943883002918
Sharpe ratio: 3.6437971864019105
=================================

 88%|████████▊ | 525/600 [10:42<01:29,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 880358.875
Final accumulative portfolio value: 8.8035888671875
Maximum DrawDown: -0.1473221445330536
Sharpe ratio: 3.6441826696664057
=================================

 88%|████████▊ | 526/600 [10:44<01:28,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 880640.0
Final accumulative portfolio value: 8.806400299072266
Maximum DrawDown: -0.14739325780023305
Sharpe ratio: 3.6445111670794987
=================================

 88%|████████▊ | 527/600 [10:49<03:02,  2.51s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 880793.0625
Final accumulative portfolio value: 8.807930946350098
Maximum DrawDown: -0.14729235358830617
Sharpe ratio: 3.6449365371861018
=================================

 88%|████████▊ | 528/600 [10:50<02:31,  2.11s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 881100.6875
Final accumulative portfolio value: 8.811006546020508
Maximum DrawDown: -0.14740908678982245
Sharpe ratio: 3.6452030370402877
=================================

 88%|████████▊ | 529/600 [10:52<02:10,  1.83s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 881235.8125
Final accumulative portfolio value: 8.812357902526855
Maximum DrawDown: -0.14727513079479104
Sharpe ratio: 3.6456621304806727
=================================

 88%|████████▊ | 530/600 [10:53<01:54,  1.64s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 881544.4375
Final accumulative portfolio value: 8.815443992614746
Maximum DrawDown: -0.1474075135788966
Sharpe ratio: 3.6458912550007976
=================================

 88%|████████▊ | 531/600 [10:54<01:44,  1.51s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 881689.1875
Final accumulative portfolio value: 8.81689167022705
Maximum DrawDown: -0.14728414881192864
Sharpe ratio: 3.6463637446151846
=================================

 89%|████████▊ | 532/600 [10:55<01:36,  1.42s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 881967.8125
Final accumulative portfolio value: 8.81967830657959
Maximum DrawDown: -0.14737621601041428
Sharpe ratio: 3.6466131419496857
=================================

 89%|████████▉ | 533/600 [10:56<01:30,  1.36s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 882172.0625
Final accumulative portfolio value: 8.821721076965332
Maximum DrawDown: -0.14733916550165993
Sharpe ratio: 3.647045149117499
=================================

 89%|████████▉ | 534/600 [10:58<01:26,  1.31s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 882371.6875
Final accumulative portfolio value: 8.82371711730957
Maximum DrawDown: -0.14732771456577232
Sharpe ratio: 3.647370957634875
=================================

 89%|████████▉ | 535/600 [10:59<01:23,  1.28s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 882637.375
Final accumulative portfolio value: 8.826374053955078
Maximum DrawDown: -0.14738310213600014
Sharpe ratio: 3.647721676175502
=================================

 89%|████████▉ | 536/600 [11:00<01:20,  1.26s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 882805.0625
Final accumulative portfolio value: 8.82805061340332
Maximum DrawDown: -0.1473128071788602
Sharpe ratio: 3.648121895386487
=================================

 90%|████████▉ | 537/600 [11:01<01:18,  1.24s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 883075.25
Final accumulative portfolio value: 8.8307523727417
Maximum DrawDown: -0.14738212543119023
Sharpe ratio: 3.6484198656967135
=================================

 90%|████████▉ | 538/600 [11:02<01:16,  1.23s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 883264.6875
Final accumulative portfolio value: 8.832647323608398
Maximum DrawDown: -0.1473319812788293
Sharpe ratio: 3.648825191618557
=================================

 90%|████████▉ | 539/600 [11:04<01:14,  1.22s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 883518.9375
Final accumulative portfolio value: 8.835189819335938
Maximum DrawDown: -0.14737346939893514
Sharpe ratio: 3.6491468572512815
=================================

 90%|█████████ | 540/600 [11:05<01:12,  1.22s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 883707.875
Final accumulative portfolio value: 8.837079048156738
Maximum DrawDown: -0.147316077982392
Sharpe ratio: 3.649550150203813
=================================

 90%|█████████ | 541/600 [11:06<01:11,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 883969.125
Final accumulative portfolio value: 8.839691162109375
Maximum DrawDown: -0.1473646615653723
Sharpe ratio: 3.6498632873396497
=================================

 90%|█████████ | 542/600 [11:07<01:10,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 884162.4375
Final accumulative portfolio value: 8.84162425994873
Maximum DrawDown: -0.14732032680542062
Sharpe ratio: 3.650247539270949
=================================

 90%|█████████ | 543/600 [11:08<01:08,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 884401.0625
Final accumulative portfolio value: 8.844010353088379
Maximum DrawDown: -0.14734735156007073
Sharpe ratio: 3.6505580271828975
=================================

 91%|█████████ | 544/600 [11:10<01:07,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 884606.9375
Final accumulative portfolio value: 8.8460693359375
Maximum DrawDown: -0.1473320438822754
Sharpe ratio: 3.650920996911169
=================================

 91%|█████████ | 545/600 [11:11<01:05,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 884828.0
Final accumulative portfolio value: 8.84827995300293
Maximum DrawDown: -0.147335642174362
Sharpe ratio: 3.6512630330564444
=================================

 91%|█████████ | 546/600 [11:12<01:04,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 885072.375
Final accumulative portfolio value: 8.850724220275879
Maximum DrawDown: -0.1473585484229415
Sharpe ratio: 3.651633667349909
=================================

 91%|█████████ | 547/600 [11:13<01:03,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 885232.5
Final accumulative portfolio value: 8.852325439453125
Maximum DrawDown: -0.14728929954511494
Sharpe ratio: 3.6520124135855068
=================================

 91%|█████████▏| 548/600 [11:14<01:02,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 885535.625
Final accumulative portfolio value: 8.855356216430664
Maximum DrawDown: -0.14740802449933876
Sharpe ratio: 3.652297903767845
=================================

 92%|█████████▏| 549/600 [11:16<01:01,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 885621.25
Final accumulative portfolio value: 8.856212615966797
Maximum DrawDown: -0.14725034627877764
Sharpe ratio: 3.6527147843069234
=================================

 92%|█████████▏| 550/600 [11:17<00:59,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 885965.25
Final accumulative portfolio value: 8.859652519226074
Maximum DrawDown: -0.1474434079346354
Sharpe ratio: 3.6529031799331766
=================================

 92%|█████████▏| 551/600 [11:18<00:58,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 886033.0625
Final accumulative portfolio value: 8.860330581665039
Maximum DrawDown: -0.14724172268391655
Sharpe ratio: 3.6533870991210207
=================================

 92%|█████████▏| 552/600 [11:19<00:57,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 886378.6875
Final accumulative portfolio value: 8.863786697387695
Maximum DrawDown: -0.14742286653988868
Sharpe ratio: 3.6535778253011033
=================================

 92%|█████████▏| 553/600 [11:20<00:56,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 886523.5
Final accumulative portfolio value: 8.865235328674316
Maximum DrawDown: -0.1472984557891429
Sharpe ratio: 3.6540774580333153
=================================

 92%|█████████▏| 554/600 [11:22<00:55,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 886771.6875
Final accumulative portfolio value: 8.867716789245605
Maximum DrawDown: -0.14735355162206987
Sharpe ratio: 3.6543458844436043
=================================

 92%|█████████▎| 555/600 [11:23<00:54,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 887010.25
Final accumulative portfolio value: 8.870102882385254
Maximum DrawDown: -0.1473678402247658
Sharpe ratio: 3.6547480480862484
=================================

 93%|█████████▎| 556/600 [11:24<00:52,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 887163.875
Final accumulative portfolio value: 8.871638298034668
Maximum DrawDown: -0.14730412059868214
Sharpe ratio: 3.655097847146303
=================================

 93%|█████████▎| 557/600 [11:25<00:51,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 887458.3125
Final accumulative portfolio value: 8.87458324432373
Maximum DrawDown: -0.14740162430872095
Sharpe ratio: 3.65539627659095
=================================

 93%|█████████▎| 558/600 [11:26<00:50,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 887586.125
Final accumulative portfolio value: 8.875861167907715
Maximum DrawDown: -0.14729489500387716
Sharpe ratio: 3.6557891319918503
=================================

 93%|█████████▎| 559/600 [11:28<00:48,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 887878.625
Final accumulative portfolio value: 8.878786087036133
Maximum DrawDown: -0.1473920517620858
Sharpe ratio: 3.656053661861664
=================================

 93%|█████████▎| 560/600 [11:29<00:47,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 888035.625
Final accumulative portfolio value: 8.880355834960938
Maximum DrawDown: -0.14730577506142928
Sharpe ratio: 3.656467669370392
=================================

 94%|█████████▎| 561/600 [11:30<00:46,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 888312.75
Final accumulative portfolio value: 8.883127212524414
Maximum DrawDown: -0.1473768640818971
Sharpe ratio: 3.6567687452658433
=================================

 94%|█████████▎| 562/600 [11:31<00:45,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 888477.0625
Final accumulative portfolio value: 8.884770393371582
Maximum DrawDown: -0.147293104381229
Sharpe ratio: 3.6571872644580954
=================================

 94%|█████████▍| 563/600 [11:32<00:44,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 888752.375
Final accumulative portfolio value: 8.887523651123047
Maximum DrawDown: -0.14736384787601942
Sharpe ratio: 3.65747835349882
=================================

 94%|█████████▍| 564/600 [11:34<00:43,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 888919.5625
Final accumulative portfolio value: 8.889195442199707
Maximum DrawDown: -0.14729960413560161
Sharpe ratio: 3.6578573401107515
=================================

 94%|█████████▍| 565/600 [11:35<00:41,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 889163.875
Final accumulative portfolio value: 8.89163875579834
Maximum DrawDown: -0.14734551005421148
Sharpe ratio: 3.658136781092507
=================================

 94%|█████████▍| 566/600 [11:36<00:40,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 889356.25
Final accumulative portfolio value: 8.893562316894531
Maximum DrawDown: -0.14731832460258687
Sharpe ratio: 3.6585010424666176
=================================

 94%|█████████▍| 567/600 [11:37<00:39,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 889569.6875
Final accumulative portfolio value: 8.895696640014648
Maximum DrawDown: -0.14732442234801246
Sharpe ratio: 3.6588246927362427
=================================

 95%|█████████▍| 568/600 [11:38<00:38,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 889797.0625
Final accumulative portfolio value: 8.897970199584961
Maximum DrawDown: -0.14733613333489926
Sharpe ratio: 3.659183394419561
=================================

 95%|█████████▍| 569/600 [11:40<00:37,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 889987.4375
Final accumulative portfolio value: 8.899874687194824
Maximum DrawDown: -0.14731241070805867
Sharpe ratio: 3.6595327089834617
=================================

 95%|█████████▌| 570/600 [11:41<00:35,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 890241.5
Final accumulative portfolio value: 8.90241527557373
Maximum DrawDown: -0.14735991966110562
Sharpe ratio: 3.659862652977333
=================================

 95%|█████████▌| 571/600 [11:42<00:34,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 890379.5
Final accumulative portfolio value: 8.90379524230957
Maximum DrawDown: -0.1472768572211176
Sharpe ratio: 3.660225274807032
=================================

 95%|█████████▌| 572/600 [11:43<00:33,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 890672.875
Final accumulative portfolio value: 8.906728744506836
Maximum DrawDown: -0.14738294708348165
Sharpe ratio: 3.6604921624894513
=================================

 96%|█████████▌| 573/600 [11:44<00:32,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 890778.75
Final accumulative portfolio value: 8.907787322998047
Maximum DrawDown: -0.1472675740014593
Sharpe ratio: 3.6608665579715356
=================================

 96%|█████████▌| 574/600 [11:46<00:31,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 891077.625
Final accumulative portfolio value: 8.910776138305664
Maximum DrawDown: -0.14739026485013074
Sharpe ratio: 3.66110894594639
=================================

 96%|█████████▌| 575/600 [11:47<00:30,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 891197.75
Final accumulative portfolio value: 8.911977767944336
Maximum DrawDown: -0.1472768711350163
Sharpe ratio: 3.661524857225916
=================================

 96%|█████████▌| 576/600 [11:48<00:28,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 891488.1875
Final accumulative portfolio value: 8.914881706237793
Maximum DrawDown: -0.14737514103827343
Sharpe ratio: 3.6618036301950907
=================================

 96%|█████████▌| 577/600 [11:49<00:27,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 891640.8125
Final accumulative portfolio value: 8.91640853881836
Maximum DrawDown: -0.14729507018653432
Sharpe ratio: 3.6622161129218234
=================================

 96%|█████████▋| 578/600 [11:50<00:26,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 891901.875
Final accumulative portfolio value: 8.919018745422363
Maximum DrawDown: -0.147355097115059
Sharpe ratio: 3.6625056126332733
=================================

 96%|█████████▋| 579/600 [11:52<00:25,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 892083.0625
Final accumulative portfolio value: 8.920830726623535
Maximum DrawDown: -0.14731268169004852
Sharpe ratio: 3.6628770361142484
=================================

 97%|█████████▋| 580/600 [11:53<00:23,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 892304.3125
Final accumulative portfolio value: 8.923043251037598
Maximum DrawDown: -0.14733058048070402
Sharpe ratio: 3.6631723279724757
=================================

 97%|█████████▋| 581/600 [11:54<00:22,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 892514.0625
Final accumulative portfolio value: 8.925140380859375
Maximum DrawDown: -0.1473257928911581
Sharpe ratio: 3.6635124643603705
=================================

 97%|█████████▋| 582/600 [11:55<00:21,  1.21s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 892709.4375
Final accumulative portfolio value: 8.927094459533691
Maximum DrawDown: -0.14731058849496204
Sharpe ratio: 3.663836960532584
=================================

 97%|█████████▋| 583/600 [11:56<00:20,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 892938.875
Final accumulative portfolio value: 8.929388999938965
Maximum DrawDown: -0.14733184309694491
Sharpe ratio: 3.6641637115205348
=================================

 97%|█████████▋| 584/600 [11:58<00:19,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 893124.3125
Final accumulative portfolio value: 8.931242942810059
Maximum DrawDown: -0.14729974219441577
Sharpe ratio: 3.664515504501536
=================================

 98%|█████████▊| 585/600 [11:59<00:17,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 893358.375
Final accumulative portfolio value: 8.933584213256836
Maximum DrawDown: -0.1473318143594653
Sharpe ratio: 3.66482643341656
=================================

 98%|█████████▊| 586/600 [12:00<00:16,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 893538.3125
Final accumulative portfolio value: 8.935382843017578
Maximum DrawDown: -0.1472970815780129
Sharpe ratio: 3.6651714266948487
=================================

 98%|█████████▊| 587/600 [12:01<00:15,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 893768.25
Final accumulative portfolio value: 8.937682151794434
Maximum DrawDown: -0.147328255468255
Sharpe ratio: 3.6654742343254516
=================================

 98%|█████████▊| 588/600 [12:02<00:14,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 893950.6875
Final accumulative portfolio value: 8.939506530761719
Maximum DrawDown: -0.1472995759088842
Sharpe ratio: 3.6658151925136813
=================================

 98%|█████████▊| 589/600 [12:04<00:13,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 894173.0625
Final accumulative portfolio value: 8.941730499267578
Maximum DrawDown: -0.147323316507861
Sharpe ratio: 3.6661213909356327
=================================

 98%|█████████▊| 590/600 [12:05<00:11,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 894363.6875
Final accumulative portfolio value: 8.943636894226074
Maximum DrawDown: -0.14730403027701444
Sharpe ratio: 3.6664641584699
=================================

 98%|█████████▊| 591/600 [12:06<00:10,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 894578.3125
Final accumulative portfolio value: 8.945782661437988
Maximum DrawDown: -0.14731822331678346
Sharpe ratio: 3.6667783294180345
=================================

 99%|█████████▊| 592/600 [12:07<00:09,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 894775.6875
Final accumulative portfolio value: 8.94775676727295
Maximum DrawDown: -0.1473078393205416
Sharpe ratio: 3.6671119349110453
=================================

 99%|█████████▉| 593/600 [12:08<00:08,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 894984.125
Final accumulative portfolio value: 8.949841499328613
Maximum DrawDown: -0.1473138031777651
Sharpe ratio: 3.6674279440718753
=================================

 99%|█████████▉| 594/600 [12:10<00:07,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 895182.9375
Final accumulative portfolio value: 8.951828956604004
Maximum DrawDown: -0.14730981403137422
Sharpe ratio: 3.6677495279618166
=================================

 99%|█████████▉| 595/600 [12:11<00:05,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 895387.875
Final accumulative portfolio value: 8.953878402709961
Maximum DrawDown: -0.14730954463260482
Sharpe ratio: 3.6680697901308377
=================================

 99%|█████████▉| 596/600 [12:12<00:04,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 895591.875
Final accumulative portfolio value: 8.955918312072754
Maximum DrawDown: -0.14731035238018286
Sharpe ratio: 3.6683905038461044
=================================

100%|█████████▉| 597/600 [12:13<00:03,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 895791.375
Final accumulative portfolio value: 8.957913398742676
Maximum DrawDown: -0.14730512173903432
Sharpe ratio: 3.6687119882061947
=================================

100%|█████████▉| 598/600 [12:14<00:02,  1.20s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 895997.9375
Final accumulative portfolio value: 8.959979057312012
Maximum DrawDown: -0.14730899293596356
Sharpe ratio: 3.6690299684336987
=================================

100%|█████████▉| 599/600 [12:15<00:01,  1.19s/it]

=================================
Initial portfolio value:100000
Final portfolio value: 896195.4375
Final accumulative portfolio value: 8.961954116821289
Maximum DrawDown: -0.1473016912297861
Sharpe ratio: 3.6693520209283497
=================================

100%|██████████| 600/600 [12:17<00:00,  1.23s/it]

### Save Model

## Test Model

### Instantiate different environments

Since we have three different periods of time, we need three different environments instantiated to simulate them.

In [26]:
policy = EIIE(time_window=4, device=device,initial_features=len(features))
policy.load_state_dict(torch.load("policy_EIIE_CH3.pt"))
if market.lower() == "us":
    policy.load_state_dict(torch.load("policy_EIIE_US.pt"))
elif market.lower() == "hk":
    policy.load_state_dict(torch.load("policy_EIIE_HK.pt"))
elif market.lower() == "ch":
    policy.load_state_dict(torch.load("policy_EIIE_CH3.pt"))
else:
    raise ValueError("market 变量必须为 'us' 或 'hk'")

environment_2025 = PortfolioOptimizationEnv(
    df_portfolio_2025,
    initial_amount=100000,
    comission_fee_pct=0.0025,
    time_window=4,
    features=features,
    normalize_df=None
)
# df_account_value_ppo, df_actions_ppo = DRLAgent.DRL_prediction(
#     model=model, 
#     environment = environment_2025)
DRLAgent.DRL_validation(model, environment_2025, policy=policy)
# environment_2021 = PortfolioOptimizationEnv(
#     df_portfolio_2021,
#     initial_amount=100000,
#     comission_fee_pct=0.0025,
#     time_window=50,
#     features=["close", "high", "low"],
#     normalize_df=None
# )

# environment_2022 = PortfolioOptimizationEnv(
#     df_portfolio_2022,
#     initial_amount=100000,
#     comission_fee_pct=0.0025,
#     time_window=50,
#     features=["close", "high", "low"],
#     normalize_df=None
# )

# for i, action in enumerate(environment_2025._actions_memory):
#     if not np.isnan(action).all():  # 如果 action 中不全是 NaN
#         if i < len(unique_dates):
#             current_date = unique_dates.iloc[i]
#         else:
#             current_date = '未知日期'  # 处理索引超出范围的情况
#         print(f"Action on {current_date} at step {i}: {action}")

# columns = ["date", "cash"] + TOP_BRL  
# results = []
unique_dates = df_portfolio_2025['date'].drop_duplicates().sort_values().reset_index(drop=True)

columns = ["date", "cash"] + TOP_BRL  
results = []

shift_value = 3  # 想统一日期往后移 4 格
actions = environment_2025._actions_memory

for i, action in enumerate(actions):
    # 如果 action 全是 NaN，我们跳过
    if np.isnan(action).all():
        continue
    
    shifted_index = i + shift_value
    if shifted_index < len(unique_dates):
        current_date = unique_dates.iloc[shifted_index]
    else:
        current_date = '未知日期'
    
    # 将 action 转成百分比字符串，比如 0.123 -> "12.30%"
    action_in_percent = [f"{x*100:.2f}%" for x in action]
    
    # 构建一行 [日期, 第一列现金比例, 后面的列是各股票比例]
    row = [current_date] + action_in_percent
    results.append(row)

# 创建 DataFrame
df_action_percent = pd.DataFrame(results, columns=columns)
print("日期统一往后移 3 格后的 DataFrame：")
print(df_action_percent.tail(10))

=================================
Initial portfolio value:100000
Final portfolio value: 621692.0625
Final accumulative portfolio value: 6.216920852661133
Maximum DrawDown: -0.14665296589509424
Sharpe ratio: 3.2338697742764295
=================================

ValueError: 10 columns passed, passed data had 8 columns

In [ ]:
# unique_dates = df_portfolio['date'].drop_duplicates().sort_values().reset_index(drop=True)

### Test EIIE architecture
Now, we can test the EIIE architecture in the three different test periods. It's important no note that, in this code, we load the saved policy even though it's not necessary just to show how to save and load your model.

In [21]:
EIIE_results = {
    "training": environment._asset_memory["final"],
    "2025": {},

}

# instantiate an architecture with the same arguments used in training
# and load with load_state_dict.
policy = EIIE(time_window=50, device=device)
policy.load_state_dict(torch.load("policy_EIIE_US.pt"))

# 2020
DRLAgent.DRL_validation(model, environment_2025, policy=policy)
EIIE_results["2025"]["value"] = environment_2025._asset_memory["final"]

# # 2021
# DRLAgent.DRL_validation(model, environment_2021, policy=policy)
# EIIE_results["2021"]["value"] = environment_2021._asset_memory["final"]

# # 2022
# DRLAgent.DRL_validation(model, environment_2022, policy=policy)
# EIIE_results["2022"]["value"] = environment_2022._asset_memory["final"]

RuntimeError: Error(s) in loading state_dict for EIIE:
	size mismatch for sequential.0.weight: copying a param with shape torch.Size([2, 4, 1, 3]) from checkpoint, the shape in current model is torch.Size([2, 3, 1, 3]).
	size mismatch for sequential.2.weight: copying a param with shape torch.Size([20, 2, 1, 2]) from checkpoint, the shape in current model is torch.Size([20, 2, 1, 48]).

In [ ]:
# unique_dates = df_portfolio['date'].drop_duplicates().sort_values().reset_index(drop=True)
unique_dates = df_portfolio_2025['date'].drop_duplicates().sort_values().reset_index(drop=True)
for i, action in enumerate(environment_2025._actions_memory):
    if not np.isnan(action).all():  # 如果 action 中不全是 NaN
        if i < len(unique_dates):
            current_date = unique_dates.iloc[i]
        else:
            current_date = '未知日期'  # 处理索引超出范围的情况
        print(f"Action on {current_date} at step {i}: {action}")

In [ ]:
filtered_df.tail()

### Test Uniform Buy and Hold
For comparison, we will also test the performance of a uniform buy and hold strategy. In this strategy, the portfolio has no remaining cash and the same percentage of money is allocated in each asset.

In [ ]:
UBAH_results = {
    "train": {},
    "2025": {},
    # "2021": {},
    # "2022": {}
}

PORTFOLIO_SIZE = len(TOP_BRL)

# train period
terminated = False
environment.reset()
while not terminated:
    action = [0] + [1/PORTFOLIO_SIZE] * PORTFOLIO_SIZE
    _, _, terminated, _ = environment.step(action)
UBAH_results["train"]["value"] = environment._asset_memory["final"]

# 2020
terminated = False
environment_2025.reset()
while not terminated:
    action = [0] + [1/PORTFOLIO_SIZE] * PORTFOLIO_SIZE
    _, _, terminated, _ = environment_2025.step(action)
UBAH_results["2025"]["value"] = environment_2025._asset_memory["final"]

# # 2021
# terminated = False
# environment_2021.reset()
# while not terminated:
#     action = [0] + [1/PORTFOLIO_SIZE] * PORTFOLIO_SIZE
#     _, _, terminated, _ = environment_2021.step(action)
# UBAH_results["2021"]["value"] = environment_2021._asset_memory["final"]

# # 2022
# terminated = False
# environment_2022.reset()
# while not terminated:
#     action = [0] + [1/PORTFOLIO_SIZE] * PORTFOLIO_SIZE
#     _, _, terminated, _ = environment_2022.step(action)
# UBAH_results["2022"]["value"] = environment_2022._asset_memory["final"]

### Plot graphics

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline 

plt.plot(UBAH_results["train"]["value"], label="Buy and Hold")
plt.plot(EIIE_results["training"], label="EIIE")

plt.xlabel("Days")
plt.ylabel("Portfolio Value")
plt.title("Performance in training period")
plt.legend()

plt.show()

In [ ]:
plt.plot(UBAH_results["2025"]["value"], label="Buy and Hold")
plt.plot(EIIE_results["2025"]["value"], label="EIIE")

plt.xlabel("Days")
plt.ylabel("Portfolio Value")
plt.title("Performance in 2025")
plt.legend()

plt.show()

In [ ]:
plt.plot(UBAH_results["2021"]["value"], label="Buy and Hold")
plt.plot(EIIE_results["2021"]["value"], label="EIIE")

plt.xlabel("Days")
plt.ylabel("Portfolio Value")
plt.title("Performance in 2021")
plt.legend()

plt.show()

In [ ]:
plt.plot(UBAH_results["2022"]["value"], label="Buy and Hold")
plt.plot(EIIE_results["2022"]["value"], label="EIIE")

plt.xlabel("Days")
plt.ylabel("Portfolio Value")
plt.title("Performance in 2022")
plt.legend()

plt.show()

We can see that the agent is able to learn a good policy but its performance is worse the more the test period advances into the future. To get a better performance in 2022, for example, the agent should probably be trained again using more recent data.